### ISSUE TITLE
Add waterbox support por Roborock Q8 Max+

### ISSUE THREAD

**Issue by jmago17** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#1025]
Hi!

I’ve successfully installed the plugin and otra running. I’ve enabled the waterbox option, since my vacuum has it, but when changing it from HomeKit, homebridge responds that the model is not compatible. The model read by HomeKit is roborock.vacuum.a73, which is not on the list of models in the file in src/models/models.ts. I would be happy to try it and report back.

**Comment by jmago17** [comment]
It works!! Thanks a lot!!

**Comment by afharo** [comment]
Thank you! 🧡
