### ISSUE TITLE
Go to target config option

### ISSUE THREAD

**Issue by antonkay** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#130]
Please consider adding an optional switch to send the vacuum to a target (e.g. garbage bin) so that it's possible to programmatically send the vacuum to the garbage bin for the purpose of emptying it.

**Comment by maisun** [comment]
That's a nice idea.
activateGoToTarget function already exist in miio, not sure it will work though

**Comment by afharo** [comment]
It does sound useful! PRs are welcome! :)

**Comment by kmengvik** [comment]
Yes, was coming here to request this feature, but found it already done. So, I'll upvote it! I have a parking garage for the Roborock in the kitchen, so I need to call it out for emptying and cleaning.

**Comment by afharo** [comment]
It totally makes sense. My concern is about how to retrieve the `X,Y` coordinates to nail the point the go-to needs to go to.

**Comment by DanielsCode** [comment]
Would be a cool feature! +1

**Comment by chinloon** [comment]
+1

**Comment by SRamsdell1** [comment]
x1

**Comment by desq42** [comment]
+1

**Comment by logix-ams** [comment]
+1

**Comment by afharo** [comment]
It should be resolved by @luc-ass in version https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.23.0
