### ISSUE TITLE
Report two issues with S5 FW 3.5.7

### ISSUE THREAD

**Issue by maisun** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#131]
Hi,
Thanks for the plugin, works very well except for two minor issues with my S5 FW 3.5.7:
1) Looks like pause doesn't work. When in cleaning, I can pause it but the switch then flips back in 2 seconds, so I can't continue afterwards. 
2) I can't seem to be able to enable Gentle mode. Reading the code S5 with 3.5.7 use the same speeds as Gen3, but Gen3 doesn't. have mopping function, maybe Gen4 is more correct?
 gen3: [
    // 0%      = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
    // 1-38%   = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 101, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 102, name: "Balanced" },
    // 61-77%  = "Turbo / Stark"
    { homekitTopLevel: 77, miLevel: 103, name: "Turbo" },
    // 78-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 104, name: "Max" }
  ],

One more suggestion:
Instead of allow any percentage of fan speed, only allow the speeds like 0, 20, 40, 60, 80, 100 for models with 5 speeds, and 0, 25, 50, 75, 100 for models with 4 speeds. Something like:
that.fanService.getCharacteristic(Characteristic.RotationSpeed).setProps({
		minStep: 20
	}).on('get', that.getSpeed.bind(that)).on('set', that.setSpeed.bind(that));

Thank you!

**Comment by afharo** [comment]
Hi @maisun!
Thank you for the detailed explanation. It does make sense. Can you create a PR with these changes when you have a moment?

**Comment by afharo** [comment]
> Instead of allow any percentage of fan speed, only allow the speeds like 0, 20, 40, 60, 80, 100 for models with 5 speeds, and 0, 25, 50, 75, 100 for models with 4 speeds. Something like:
> that.fanService.getCharacteristic(Characteristic.RotationSpeed).setProps({
> minStep: 20
> }).on('get', that.getSpeed.bind(that)).on('set', that.setSpeed.bind(that));

Hi @maisun I've published a candidate including these changes at `homebridge-xiaomi-roborock-vacuum@next`.
Please, let me know if this works for you.

**Comment by maisun** [comment]
Hi @afharo 
Thanks for the great work and sorry for the late reply! As I wrote in another thread, I did some changes to the code myself and published to NPM:
https://www.npmjs.com/package/homebridge-roborock
I'm not sure what do you mean by PR? I have marked all changes in the code by comments, and below is the summary of my version:
1) Changed the logic to periodically pull status from the device, make the accessories more responsive. 
2) Added support for go to target function
3) The room switches can be used to select multiple rooms before start cleaning. When cleaning fan is powered on, it automatically detects if the device should do a full house clean or room clean based on if any room is enabled for cleaning
4) Fixed the resume function so now it's possible to resume from room cleaning mode
5) More validation logic added together with some other small improvements
6) Fixed no gentle mode for Roborock S5
7) Auto configure the minimal step for fan service so for models with 4 speeds it will be 25% each level and for models with 5 speeds it will be 20% each level. It is no longer possible to choose other percentages. 
Maybe some of the changes can be merged with this plugin? I know some were asking for 2) and 3). Thanks and have a nice weekend

**Comment by afharo** [comment]
> I'm not sure what do you mean by PR?

PR stands for Pull Request. Here you have an explanation of how a typical Git flow works: https://guides.github.com/introduction/flow/. You can push your changes to a fork of this repository (using the fork button in the top right corner) and create a Pull Request.

> I did some changes to the code myself and published to NPM:
> https://www.npmjs.com/package/homebridge-roborock

I would say it would be better if we all work alongside to improve the same repo rather than publishing improvements in separate NPM modules. In the long run, we will all benefit from the joined effort #opensource ❤️

**Comment by afharo** [comment]
I'm sure folks will love to see many of your improvements carried over to this module.
