### ISSUE TITLE
[Feature Request] Multi-Zone switch

### ISSUE THREAD

**Issue by normen** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#132]
Hey,

it would be cool if I could assign a switch not only for single zones but for a combination of zones as well. It seems like the miio API can send multiple zone/room IDs per request so I guess its just a matter of supporting arrays in the config file?

Cheers for this plugin,
Normen

**Comment by github9984** [comment]
any updates on this?

**Comment by normen** [comment]
What is "any updates on this" supposed to mean? There wasn't even an answer to this thread.

**Comment by maisun** [comment]
I've made some changes to allow this, try homebridge-roborock.
Also added a few other fixes

**Comment by afharo** [comment]
@maisun I think we will all benefit if you submit a PR to this project rather than each one of us publishing clones with minor changes

**Comment by normen** [comment]
> @maisun I think we will all benefit if you submit a PR to this project rather than each one of us publishing clones with minor changes

Just merge it back ;) Getting synergy going in Open Source is hard. It starts with the choice of IDE and ends with design choices. For many it seems so much easier to just do it the way they're used to and start a new project in "their" language or "their" development environment or "their" favorite UI library - instead of taking the time and looking into whatever system is in place already. And sometimes thats even for the better, making way for new ideas and options.

**Comment by maisun** [comment]
Hi, the pull request: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/200
Please approve :)

**Comment by afharo** [comment]
@normen I believe this request is covered already in the latest version.
You can see in the docs you can now define multiple zones for a single switch.

```
  "zones": [
 {
      "name":"Family Room (x2)",
      "zone":[[25000,25000,32000,32000,2]]
    },
    {
      "name":"Bedroom",
      "zone":[[21000,32000,24000,37000,1]]
    },
    {
      "name":"Bedroom & Family Room",
      "zone":[ [21000,32000,24000,37000,1],  [25000,25000,32000,32000,1]]
    }
  ]
```

Can you confirm if this is what you meant with this issue? If so, would you mind closing this issue?

@maisun's alternative (really interesting to me and I think it's worth exploring and implementing it for future releases) is that you can select multiple rooms ON, but the vacuum won't start cleaning until you hit "clean". This way you select as many combinations as you like.

Thank you both.

**Comment by normen** [comment]
The way I see the use case is that I sometimes know that I can only clean some of the rooms now (e.g. kids are out, wife is watching TV) so I can't really tell every combination I'll need beforehand.

So yeah, really something more dynamic would be nice. I mean theres a switch for every room already. The easiest from a user perspective would be to simply turn on those switches for the rooms you want cleaned. Then the plugin would handle making that a multi-room request.

It wouldn't really matter if that results in multiple requests being sent to the vacuum I suppose, why add the additional confirmation via clean. If its all sent in an automated scene the requests will be in before the vacuum even moves. And if the user manually selects one and then the other room then he'll quickly discover that this "restarts" the cycle for those selected rooms.

**Comment by MirkoKas** [comment]
Would love such a feature for rooms so much. This way I could also set an HomeKit automation for cleaning multiple specific rooms. @afharo would the config for zones you mentioned above also work for rooms and if yes what’s the configuration?

**Comment by afharo** [comment]
@MirkoKas based on @maisun's job, we might be able to change the current behaviour: 

Instead of the cleaning to start the moment you select a room, we could switch the rooms on/off and when the vacuum is started, it would clean all the selected rooms or perform a full clean if no rooms/zones are selected.

**Comment by normen** [comment]
> Instead of the cleaning to start the moment you select a room, we could switch the rooms on/off and when the vacuum is started, it would clean all the selected rooms or perform a full clean if no rooms/zones are selected.

It will be hard to force HomeKit to switch on the main switch last when all of them are in one automation...

**Comment by afharo** [comment]
@normen true! we might need to test it. Worst case scenario, we add a small 200ms delay to the start command to, hopefully, allow HomeKit to hit all the other switches on time :)

**Comment by MirkoKas** [comment]
I checked the pull request by @maisun but I’m not quite sure what the status is because the last activity was about 2 month ago. 
Anyway I will be happy when the ability to group multiple rooms will be available. 👍🏼

**Comment by afharo** [comment]
@maisun's PR was _malformed_ in the sense of it entirely replacing the existing code with his version, removing some features this module provided on top of his changes.

Ideally, a Pull Request should only add/modify the intended enhancements/fixes. That is why it cannot be merged as-is. I kept it open as a reference for the all the goodness it adds, but someone needs to create a new Pull Request containing only those changes and not removing existing features.

I will eventually do it when I have a spare moment but, if anyone else wants to do it before I do, I'll be delighted to accept the changes :)
