### ISSUE TITLE
Resume from pause doesn't work under room cleaning mode

### ISSUE THREAD

**Issue by maisun** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#133]
Hi,

Looks like when resume room cleaning from pause doesn't work.
Checked the code looks like resume uses the same command to start full house cleaning.
Most likely the room cleaning resume uses different command.

**Comment by maisun** [comment]
Recall for zone cleaning the call is "resume_zoned_clean"
Maybe it is "resume_segment_clean"?

**Comment by maisun** [comment]
The API is documented here: https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/segment_clean.md

**Comment by afharo** [comment]
This might be fixed by @ileodo 's PR #317
