### ISSUE TITLE
Error setCleaning - failed to set cleaning to true

### ISSUE THREAD

**Issue by stanislawbejm** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#141]
Hello,

I have a problem with room cleaning. My "Xiaomi Vacuum 1S" support room cleaning. But logs show error (attached).

![error](https://user-images.githubusercontent.com/29429399/78013636-0d3a0580-7347-11ea-9d96-1efe18c3bf72.png)

**Comment by afharo** [comment]
Does that model support room cleaning via the app?

**Comment by afharo** [comment]
Sorry, I missed your original part where you say your robot DOES support room cleaning...

**Comment by afharo** [comment]
I finally had the time to look deeper at this...
I think the next release might be able to fix this bug: #210

**Comment by afharo** [comment]
Would you mind trying with installing this beta version `homebridge-xiaomi-roborock-vacuum@0.11.0-0`?
