### ISSUE TITLE
Errors don't clear up and keep showing up

### ISSUE THREAD

**Issue by glowfishDE** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#162]
Hi,

i´m getting the following error now and then until i restart homebridge to get rid of the error:

[4/29/2020, 2:44:48 PM] [Roborock S50 UNTEN] WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - charger-offline, Charger is offline

Dock has power and the connectors are clean. The robot is charging according to the MII Home App.

No idea why it is spawning that error.

**Comment by barneyonline** [comment]
I also get a reoccurring error for my S5:

[Robot Vaccum] WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - 8, Make sure there are no obstacles around the vacuum.

**Comment by AlexG-78** [comment]
I also get on a regular basis also warnings:
My vacuum is docked and charged and nobody touched it

WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - 3, Try moving the vacuum to a different place.
Restarting homebridge resolves the issue.

**Comment by glowfishDE** [comment]
Maybe this additional info is useful and others can confirm: I only get these errors after i let the robots clean something (full cleaning or room selective).

When i restart homebridge and the robots just sit in their dock the errors are never occuring in my log.

**Comment by AlexG-78** [comment]
It only happens once I started and finished room cleaning

**Comment by afharo** [comment]
It seems like the robot keeps emitting past errors. We may need to investigate if there's a way to flush them from the memory once logged.
Thanks for reporting it and all the additional details!

**Comment by asbesto01** [comment]
same for me, xiaomi mi robot 1s, check screen! 
even if Homebridge shows this error, the vacuum works perfectly.

<a href="https://ibb.co/wpk6Njw"><img src="https://i.ibb.co/KVPyjSL/Schermata-2020-05-01-alle-20-10-54.png" alt="Schermata-2020-05-01-alle-20-10-54" border="0"></a>

**Comment by afharo** [comment]
It should be fixed in `homebridge-xiaomi-roborock-vacuum@next`. Can you test and confirm, please?

**Comment by barneyonline** [comment]
@afharo Works for me 😄 Errors no longer continue appearing

**Comment by glowfishDE** [comment]
affirmative - so far i couldnt see any errors too. Closing the bug - thanks alot @afharo :)

**Comment by glowfishDE** [comment]
Correction: Might be a different problem, but i am now getting old errors spawned again, even the problem (dirty contacts / no charging) was solved hours ago:

[5/4/2020, 3:45:08 PM] [Roborock S50 UNTEN] WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - 13, Couldnt charge properly. Make sure the charging surfaces are clean.
[5/4/2020, 3:45:38 PM] [Roborock S50 UNTEN] WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - 13, Couldnt charge properly. Make sure the charging surfaces are clean.

**Comment by afharo** [comment]
Hmmm @glowfishDE,
I'm not sure what it can be...

Are you sure you are running the `@next` version? 
Can you run `npm -g list homebridge-xiaomi-roborock-vacuum` to check the installed version? If it's `0.8.0-...` then you are running the version containing the changes.

**Comment by glowfishDE** [comment]
Hi,

the above command gives me:

/homebridge # npm -g list homebridge-xiaomi-roborock-vacuum
/usr/local/lib
`-- (empty)

**Comment by afharo** [comment]
hmm... maybe without the `-g`? or by adding `sudo`?

**Comment by glowfishDE** [comment]
Hah!

npm list homebridge-xiaomi-roborock-vacuum
/homebridge
`-- homebridge-xiaomi-roborock-vacuum@0.7.7 



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.13.4 -> 6.14.5      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.5   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Obviously it didnt update correctly ?

Strange because normally my homebridge-config-ui-x tells me there is an update available and i update quiet frequently.

Ill update and report again

**Comment by afharo** [comment]
> Strange because normally my homebridge-config-ui-x tells me there is an update available and i update quiet frequently.

Yeah... the `@next` release is not `@latest`. That's why the UI doesn't tell you there's a new version ;)

It's kind of a _beta_ version :)

If you want to install it, you'll need to enforce it by running `npm install homebridge-xiaomi-roborock-vacuum@next` :)

**Comment by glowfishDE** [comment]
npm list homebridge-xiaomi-roborock-vacuum
/homebridge
`-- homebridge-xiaomi-roborock-vacuum@0.8.0-2

Ok - lets see what happens next.. ill re-open if its occuring again. Thanks Alejandro

**Comment by Phoenix-DH** [comment]
Hey, only as info:
I got still this error in version v0.11.2

**Comment by afharo** [comment]
😭 
Thanks for confirming... reopening then... 🤦

**Comment by Phoenix-DH** [comment]
Thanks!

**Comment by afharo** [comment]
It should finally be fixed in `homebridge-xiaomi-roborock-vacuum@0.11.4`.

**Comment by Phoenix-DH** [comment]
Will try it.... and let youi know if it is not working ....

**Comment by afharo** [comment]
Thank you! And please, feel free to reopen the issue if you find it's not working
