### ISSUE TITLE
Make afharo Owner

### ISSUE THREAD

**Issue by afharo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#166]
Hi @nicoh88 

I'd like to set up some labels and, possibly, some automations to (hopefully) set up an automated test suite for every PR and NPM publisher. But I can't do so if I don't have access to the settings tab in this repo. Apparently, the `maintainer` role I currently have is not enough. 

Would you mind _increasing my rank_? 😅

**Comment by nicoh88** [comment]
**Transfer ownership**
_Transfer this repository to another user or to an organization where you have the ability to create repositories._

![7CCB9A51-0CD4-4DED-8D5B-4931F1F8B4DB](https://user-images.githubusercontent.com/264264/80872515-b495b980-8cb2-11ea-9139-e95c2019c0b2.jpeg)

**Comment by afharo** [comment]
oh! I'm not talking about transferring. I'm ok with it being under your account in `nicoh88`. It's your baby! You started it :)
Is there any way to make me co-owner instead of transferring it entirely?
I've been playing around and it looks like it doesn't for personal repos?

Maybe (thinking ahead), we want to create an organisation that will own this and the `miio` repo?

**Comment by nicoh88** [comment]
Hmm, no problem. A new organisation is too much work, for that or?

I would transfer to you!

**Comment by afharo** [comment]
I created the organisation https://github.com/homebridge-xiaomi-roborock-vacuum/ and invited you in there.

Hopefully, we can both be owners of that organisation :)

Once in, I'm sure you can transfer the ownership of this repo and miio to that organisation :)

**Comment by nicoh88** [comment]
`Moving repository to homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum. This may take a few minutes.`

`Moving repository to homebridge-xiaomi-roborock-vacuum/miio. This may take a few minutes.`

**Comment by afharo** [comment]
I see it has been moved now! Thank you!
I made you owner of the organisation as well so you can fully admin everything in there as well :)
Closing this issue.
