### ISSUE TITLE
Zone Cleaning vs Room Cleaning

### ISSUE THREAD

**Issue by misanthrophy** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#174]
Hello,

Right now I am still using 0.7.1 with room cleaning support, which works just fine under homebridge@1.0.4

I am now curious if I should update to the current version which no lo longer supports that, but instead uses zone cleaning with the option to add amount of times for cleaning.

Is there any advantage in general with that option/new version and is there an easy way to follow how to get the coordinates for each room? (I saw in one issue post something with a API URL of the roborock?) 
I am using the Roborock S50 with mop function! 

Thanks in advance!

**Comment by AlexG-78** [comment]
Hi,

the latest version still supports room cleaning functionality. The Zone cleaning function was added in the latest version. So it's up to you which function you would like to use. 
the zone cleaning feature is a bit tricky to set up as you need to figure out the appropriate coordinates for your zones. If you use any flavor of Valetudo, you can use the Web API to get the coordinates of your zones. http://rockrobo/api/get_config
You still need to figure out the right rotation of the map otherwise your vacuum goes to a wrong location.

Hope this helps

**Comment by misanthrophy** [comment]
Hi @AlexG-78 

I am afraid, because when I installed the latest version of the plugin, my rooms dissappeared from the device section in Home. I then rolled back to the version mentioned above and they were again there and working. I did not touched my config.json in the meantime, so I don't know what happens there. :-(

**Comment by AlexG-78** [comment]
I am sorry but I cannot halp on this. Maybe your config.json is not correct. What I did was to figure out the room IDs by using the autoroom function, after getting the right IDs, I set it back to manual with "autoroom": false
Maybe that helps

**Comment by afharo** [comment]
Hi @misanthrophy can you share your config file (obscure the IP and token if you like). I want to check what might be happening as both options should be supported in any of the newest versions 🤔

**Comment by misanthrophy** [comment]
sorry, missed your message:

{
            "name": "Staubsauger",
            "ip": "192.XXX.XXX.XX",
            "token": "XXXXXXXXXXXXX",
            "waterBox": true,
            "pause": true,
            "dock": true,
            "cleanword": "Reinigung",
            "autoroom": true,
            "rooms": [
                {
                    "name": "Wohnzimmer",
                    "id": 16
                },
                {
                    "name": "Küche",
                    "id": 17
                },
                {
                    "name": "Flur",
                    "id": 18
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }

**Comment by afharo** [comment]
oh! I think you don't need `"autoroom": true,` since you already have the `"rooms"` array. Can you try if that fixes the issue for you?

**Comment by afharo** [comment]
@misanthrophy due to inactivity. I'm going to close this issue. If you feel like the issue is not fixed, feel free to reopen it, please :)
