### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by funkyremi** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#175]
Hello,
I have a Roborock s6 pure and it's recognized as roborock.vacuum.a08 in the logs so I have the speed issue : `WAR changedSpeed | roborock.vacuum.a08 | Speed was changed to 102%, this speed is not supported`

**Comment by arisarts** [comment]
Hi.
I am also facing the same speed issue but with Xiaomi Mi Robot Vaccum 1st Generation: WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 75%, this speed is not supported.
When I start and stop through Homekit it clears this alarm but it is reappearing .

**Comment by BobVanceReef** [comment]
Hello,
I have the same issue with my Xiaomi Roborock S4. When the vacuum is docked and off, I get these logs:
`[Xiaomi Roborock S4] WAR changedSpeed | roborock.vacuum.s4 | Speed was changed to 102%, this speed is not supported`
When the vacuum is running, I get the following log:
`[Xiaomi Roborock S4] INF getSpeed | roborock.vacuum.s4 | Fanspeed is 102 over miIO. Converting to HomeKit`

**Comment by afharo** [comment]
Hi all! Thank you for your messages!

It looks like your models are not in the _known models_ list yet: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/models/models.js

Usually, it's as simple as adding the model as you see it in the logs you reported (`roborock.vacuum.a08`, `rockrobo.vacuum.v1` and `roborock.vacuum.s4`, respectively) and map it to the right speed mapping (https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/models/speedmodes.js).

By default, it assigns the `gen1`, and that is why it's telling you that speed doesn't match the expected modes. 

You can change the modes in the app and see the reported mode in the logs. That will help you figure out what's the `gen` in speedmodes.js your model maps to.

You can test it by manually editing the file in your `node_modules/homebridge-xiaomi-roborock-vacuum/models/models.js`. Then you can create a Pull Request adding your model mapping or tell me the mappings you found it works best.

**Comment by mrreview** [comment]
Hello! first of all thank you for this plugin! its really cool.

I also have the same issue with the speed. I have the Mi Vacuum V1 (rockrobo.vacuum.v1) I see that is available on models.js and also mapped to gen1 speedmodes.js 
I tested changing between all the cleaning mode on the Mi Home APP and then I can see those speeds in homebridge log:

```
[5/19/2020, 12:31:06 PM] [Mi Robot] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 75 over miIO. Converting to HomeKit
[5/19/2020, 12:31:07 PM] [Mi Robot] WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 75%, this speed is not supported
[5/19/2020, 12:37:22 PM] [Mi Robot] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 100 over miIO. Converting to HomeKit
[5/19/2020, 12:37:37 PM] [Mi Robot] WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 100%, this speed is not supported
```

As you can see these modes, 75 (turbo) and 100 (max) aren't available in speedmodes.js... what can I do?

Thank you

**Comment by afharo** [comment]
@mrreview Thank you for the detailed explanation.
I published an update for that model in `homebridge-xiaomi-roborock-vacuum@0.8.4`
