### ISSUE TITLE
no autoroom's detected

### ISSUE THREAD

**Issue by iGodPhil** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#182]
Hey i'm unable to creat the autorooms. I have the S5 model and added the autoroom option to my config.json file with an array. Afterwards I have created the timer with the selected rooms into my xiaomi home app and deactivated the timer. Then I restarted the homebridge service but no rooms were added to my config.json. So what do I wrong? 
I am unsure what do you mean with submit the timer.

And my second question is what the cleanword do?

> 
>       {
>          "name":"Roborock Oben",
>          "ip":"192.168.178.***",
>          "token":"*******",
>          "pause":false,
>          "dock":true,
>          "accessory":"XiaomiRoborockVacuum",
>          "cleanword":"Staubi oben",
>          "autoroom":[]
>       }
>

**Comment by afharo** [comment]
I can see in the config you have an empty array in `autoroom`. It is supposed to contain the names of the rooms in the same order as you selected the rooms in the timer (https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#semi-automatic).

Re the `cleanword`, it is used to name the switch to clean the room. in your case, they will be named after `"Staubi oben ROOM_NAME"` where ROOM_NAME is each of the names you listed in the `"autoroom"` array.

**Comment by iGodPhil** [comment]
Thanks for your help. Now everthing works.
