### ISSUE TITLE
0.8.0

### ISSUE THREAD

**Issue by netRunner0** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#184]
After updating to version 0.8.0, Homekit became frightened to slow down with this instance of Homebridge, right down to "no answer" for all devices in the room.

Going back to the previous version solves the problem

**Comment by afharo** [comment]
Are you getting any errors in the logs? What version of `homebridge` are you running?

**Comment by bedrin** [comment]
In fact I think I have the same issue now. Even when running latest homebridge 1.0.4

There're no errors in logs but Apple Home shows "No response" for all accessories from this plugin.
If I drill down to accessory (say occupancy sensor or pause switch) it eventually comes up.

Again logs are perfectly fine:
```
[5/11/2020, 9:46:49 PM] [Vacuum] INF getBatteryLow | roborock.vacuum.e2 | Batterylevel is 100%
[5/11/2020, 9:46:49 PM] [Vacuum] INF getSpeed | roborock.vacuum.e2 | Fanspeed is 68 over miIO. Converting to HomeKit
[5/11/2020, 9:46:49 PM] [Vacuum] INF getSpeed | roborock.vacuum.e2 | Fanspeed is 68 over miIO "Balanced" > HomeKit speed 60%
[5/11/2020, 9:46:49 PM] [Vacuum] INF getCleaning | roborock.vacuum.e2 | Cleaning is false
```

**Comment by bedrin** [comment]
One suspicious message:
```
[5/11/2020, 9:57:08 PM] [Vacuum] DEB getServices | undefined
```

**Comment by afharo** [comment]
`0.8.1` doesn't seem to have that issue. Maybe it's a communication issue for `homebridge@1.x.x`?

**Comment by bedrin** [comment]
Other plugins (I have Xiaomi air purifier and humidifier) work fine with 1.0.4

**Comment by bedrin** [comment]
Sometimes it works after I restart homebridge. Probably some kind of race issues when I query the state before it's fully initialized

**Comment by afharo** [comment]
I personally started having issues with `homebridge-webos-tv`. But it's true that after a few restarts with `1.0.4` (nothing else changed), it worked smooth (I've been actually running `1.0.4` for almost a week and `v0.8.0-6` without an issue although it took a while until it settled down)...

> Sometimes it works after I restart homebridge. Probably some kind of race issues when I query the state before it's fully initialized

Maybe that's the reason...

**Comment by afharo** [comment]
I've created https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/187 to investigate about that issue

**Comment by diwiesign** [comment]
The same here. After switching back to V0.7.7 with HB V1.0.4 it seems stable again.
