### ISSUE TITLE
Stable restarts

### ISSUE THREAD

**Issue by afharo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#187]
It looks like some restarts make the plugin quite unstable (reporting in the Home app "No Response") every now and then. But it works again after some restarts.

Let's try to find out if there's any race condition during startup.

**Comment by bedrin** [comment]
Hi @afharo .

I used bisect approach to find out what's wrong - this guy looks like a smoking gun to me:
```
      // Now that we know the model, amend the steps in the Rotation speed (for better usability)
      const minStep = 100 / (this.findSpeedModes().length - 1);
      this.services.fan
        .getCharacteristic(Characteristic.RotationSpeed)
        .setProps({ minStep });
```
