### ISSUE TITLE
Stuck Homekit after install this prject tj homebridge

### ISSUE THREAD

**Issue by dmtrten** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#192]
My Homekit stuck ""loading accessories and scenes", Any help

**Comment by afharo** [comment]
There was a known issue but was fixed yesterday evening with `0.8.3`: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/CHANGELOG.md#083

Are you running the latest version?

**Comment by dmtrten** [comment]
I was install yestaday, moning. But don't know which ver., but it was last ver in time. 
Now i have stuck homekit, do you now how it fix?

**Comment by afharo** [comment]
it depends on your installation (if global or not), to find out, run
`npm -g list homebridge-xiaomi-roborock-vacuum` and `npm list homebridge-xiaomi-roborock-vacuum` (mind the `-g` that stands for global).

Then, to upgrade the module to the latest, you can run `npm install homebridge-xiaomi-roborock-vacuum@latest` (or `npm -g install homebridge-xiaomi-roborock-vacuum@latest` if global)

**Comment by afharo** [comment]
This issue has been staled for 10 days. @dmtrten I'm going to close it. If you feel like this is still an issue, please feel free to reopen it :)
