### ISSUE TITLE
Vacuum doesn’t clean when triggered by time automations.

### ISSUE THREAD

**Issue by adamrzanek** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#195]
I have simple time automation in home app to clean my apartment. Most of the time the vacuum doesn’t work with this. Resetting HomeKit hubs and router is fixing the problem for some time, usually one day or so . But the problem reappearing again and again...

**Comment by afharo** [comment]
It might be related to #146.
Can you try installing the beta version `homebridge-xiaomi-roborock-vacuum@next`?

**Comment by adamrzanek** [comment]
> It might be related to #146.
> Can you try installing the beta version `homebridge-xiaomi-roborock-vacuum@next`?

Thanks i will try later when I get home

**Comment by afharo** [comment]
It should be fixed in the latest `0.9.0` release. Please, feel free to reopen if still happening

**Comment by adamrzanek** [comment]
It’s crashing totally for me now. 

CMD: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest

npm WARN homebridge-xiaomi-roborock-vacuum@0.10.1 requires a peer of homebridge@>=0.4.45 but none is installed. You must install peer dependencies yourself.

npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/cli/index.js
npm ERR! dest /usr/local/bin/miio
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/cli/index.js' -> '/usr/local/bin/miio'
npm ERR! File exists: /usr/local/bin/miio
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-22T17_35_20_670Z-debug.log

Command failed. Please review log for details.

**Comment by afharo** [comment]
can you try removing ` /usr/local/bin/miio`?
It looks like an installation issue

**Comment by adamrzanek** [comment]
Sorry, I’m totally new to this. How can I do this?

**Comment by afharo** [comment]
`rm -f /usr/local/bin/miio` 😉

**Comment by adamrzanek** [comment]
pi@homebridge:/var/lib/homebridge $ sudo rm -f /usr/local/bin/miio
pi@homebridge:/var/lib/homebridge $ sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest
npm WARN saveError ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN homebridge-xiaomi-roborock-vacuum@0.10.1 requires a peer of homebridge@>=0.4.45 but none is installed. You must install peer dependencies yourself.
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No README data
npm WARN homebridge No license field.

+ homebridge-xiaomi-roborock-vacuum@0.10.1
updated 1 package and audited 471 packages in 14.997s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

pi@homebridge:/var/lib/homebridge $

**Comment by afharo** [comment]
brilliant! now you need to restart `homebridge`

**Comment by afharo** [comment]
oh! wait!

**Comment by afharo** [comment]
`sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@next`

**Comment by adamrzanek** [comment]
Thank you!

**Comment by afharo** [comment]
Thank you for testing! @adamrzanek
