### ISSUE TITLE
Move the miio library to a folder in this repo

### ISSUE THREAD

**Issue by afharo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#196]
We are maintaining our own version of the miio library because the original dev stopped accepting PRs. 

Maybe it makes sense to copy the library (the version in https://github.com/homebridge-xiaomi-roborock-vacuum/miio) to this repo so it's easier to maintain :)

**Comment by bedrin** [comment]
Probably worth copying https://github.com/tinkerhub/abstract-things as well

**Comment by bedrin** [comment]
And removing everything unrealted to non vacuum cleaners in this case

**Comment by afharo** [comment]
Do you think we need to go that low? Personally, I never found myself needing to change anything in that library (so far).

+1 on removing anything unrelated to vacuum cleaners during the migration process.

I think I have some time this Friday to do so :)

**Comment by bedrin** [comment]
https://github.com/tinkerhub/abstract-things/pull/5

**Comment by afharo** [comment]
Personally, I don't think that's a change that requires moving the library. If you want to ensure the library `debug` logs the Things library logs, you can simply set the environment variable `DEBUG=thing:*`. More documentation about the debug library: https://www.npmjs.com/package/debug

**Comment by afharo** [comment]
And we can still publish a fork of it if really needed.

The reason for moving `miio` though, is because we are constantly modifying that library. The development of this plugin is tightly bound to that library and, on many occasions, it means changing both libraries.

**Comment by bedrin** [comment]
Looks like you’ll have a busy Friday )

**Comment by afharo** [comment]
Hahaha! I had a day off today, but my girlfriend is working so... having fun here :D
