### ISSUE TITLE
S5 Max is configured, but cannot be reached.

### ISSUE THREAD

**Issue by Borgan1** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#198]
My configuration:
-----------------------
Running a homebridge implementation delivered with deCONZ on a RASP Pi4 with a conbee 2 Stick.
System ist up to date.
I've tried to implement my Roborock S5 Max (Firmware 01.07.80), named "Frau Boedeker", to Apple Homekit.
In Homekit and EVE I can see the Robot and several switches, but all of them are off or "No connection to device" ist shown.

Is this a real issue of the software stack or a problem between my ears :-D.

I realy need some help.

added to config.json:
----------------------------
"accessories": [
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Frau Boedecker",
  "ip": "192.168.178.47",
  "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "pause": true,
  "dock": true,
  "waterBox": true
 }
],

What I've installed as root:
-----------------------------------
root@phoscon:~# sudo npm list -g --depth=0
/usr/lib
├── homebridge@1.1.0
├── homebridge-hue@0.11.42
├── homebridge-xiaomi-roborock-vacuum@0.8.3
├── miio@0.15.6
└── npm@6.14.4

setup:
--------
npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
npm install -g miio@latest --unsafe-perm

Whats inside the syslog (restart homebridge, open Home app on the iPhone):
-------------------------------------------------------------------------------------------------------
May 19 10:10:04 phoscon deCONZ-homebridge.sh[6594]: [2020-5-19 10:10:04] Got SIGTERM, shutting down Homebridge...
May 19 10:10:04 phoscon systemd[1]: Stopping deCONZ: ZigBee gateway -- homebridge Service...
May 19 10:10:04 phoscon systemd[1]: deconz-homebridge.service: Main process exited, code=killed, status=15/TERM
May 19 10:10:09 phoscon systemd[1]: deconz-homebridge.service: Succeeded.
May 19 10:10:09 phoscon systemd[1]: Stopped deCONZ: ZigBee gateway -- homebridge Service.
May 19 10:10:09 phoscon systemd[1]: Started deCONZ: ZigBee gateway -- homebridge Service.
May 19 10:10:15 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:15] Loaded config.json with 1 accessories and 1 platforms.
May 19 10:10:15 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:15] ---
May 19 10:10:16 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:16] Plugin /usr/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
May 19 10:10:16 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:16] The plugin "homebridge-hue" requires a Homebridge version of ^0.4.50 which does not satisfy the current Homebridge version of 1.1.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
May 19 10:10:17 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:17] Loaded plugin: homebridge-hue@0.11.42
May 19 10:10:17 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:17] Registering platform 'homebridge-hue.Hue'
May 19 10:10:17 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:17] ---
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Loaded plugin: homebridge-xiaomi-roborock-vacuum@0.8.3
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] ---
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Loading 1 platforms...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Initializing Hue platform...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] homebridge-hue v0.11.42, node v12.16.3, homebridge v1.1.0
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] warning: not using recommended node version v12.13.0 LTS
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] warning: not using recommended homebridge version v0.4.50
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Loading 1 accessories...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Frau Boedecker] Initializing XiaomiRoborockVacuum accessory...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] warning: latest version: homebridge-hue v0.11.68
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.75, api v1.16.0
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.70
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Daylight: set homekit sunrise from undefined to Tue May 19 2020 05:21:10
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Daylight: set homekit sunset from undefined to Tue May 19 2020 21:26:50
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Daylight: set homekit light level from 0.0001 lux to 100000 lux
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Phoscon-GW: 7 accessories
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Phoscon-GW'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] [Hue] Phoscon-GW: 2 services
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Extended color light 1'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Daylight'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Balkontür Büro'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Multisensor 1'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Multisensor 2'...
May 19 10:10:18 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:18] Initializing platform accessory 'Wassersensor'...
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: Setup Payload:
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: X-HM://yyyyyyyyyyyyyyyyyyy
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: #033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#............
.........
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: #033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]:                        
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]:     ┌────────────┐
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]:     │ AAA-BB-CCC │
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]:     └────────────┘
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]:                        
May 19 10:10:19 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:19] Homebridge is running on port 51826.
May 19 10:10:20 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:10:20] [Frau Boedecker] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

commentary: the restart has finished and now  I am starting Apple Home app on my iPhone

May 19 10:12:22 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:12:22] [Frau Boedecker] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:51] [Frau Boedecker] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:765:32)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at XiaomiRoborockVacuum.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:771:31)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:49
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at On.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:26)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at On.emit (events.js:310:20)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]:     at Array.forEach (<anonymous>)
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:51] [Frau Boedecker] ERR getWaterSpeed | No vacuum cleaner is discovered yet.
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:51] [Frau Boedecker] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:51] [Frau Boedecker] ERR getPauseState | No vacuum cleaner is discovered yet.
May 19 10:13:51 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:51] [Frau Boedecker] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
May 19 10:13:53 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:13:53] [Frau Boedecker] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:14] [Frau Boedecker] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:765:32)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at XiaomiRoborockVacuum.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:771:31)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:49
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at On.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:26)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at On.emit (events.js:310:20)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]:     at Array.forEach (<anonymous>)
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:14] [Frau Boedecker] ERR getWaterSpeed | No vacuum cleaner is discovered yet.
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:14] [Frau Boedecker] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:14] [Frau Boedecker] ERR getPauseState | No vacuum cleaner is discovered yet.
May 19 10:14:14 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:14] [Frau Boedecker] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
May 19 10:14:16 phoscon deCONZ-homebridge.sh[5963]: [2020-5-19 10:14:16] [Frau Boedecker] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

**Comment by afharo** [comment]
Hi @Borgan1, can you make sure the IP and the token are correct?

**Comment by Borgan1** [comment]
Hi @afharo, I've double checked it again.
Ping is possible and I've extracted the token by two different ways that are described on this page

https://forum.smartapfel.de/forum/thread/370-xiaomi-token-auslesen/

**Comment by Borgan1** [comment]
Any suggestions for further debugging?

**Comment by Borgan1** [comment]
OK....further information I guess I've used the wrong token (mi app).
But now I am using the Roborock app, so I am guessing, the token has changed during the reinstallation with the Roborock app.
Is there a way to extract the token from the Roborock app?

**Comment by afharo** [comment]
That is a known issue: switching to the Roborock app resets the token. In #104, some folks are discussing their attempts to retrieve the token from that app.

If you don't mind, I'll close this issue and we can follow up in that other issue instead :)

**Comment by roboterm** [comment]
Had the same ERR message.
I noticed that my S6 had a new IP instead of I told the router not to change it.
So I refreshed my config with the new IP and the handshake timeout was gone.
