### ISSUE TITLE
Configuration error or UI?

### ISSUE THREAD

**Issue by EvelRus** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#218]
Good afternoon!
I apologize in advance for the language - Google translator)

In general, I found an error in the configurator. If you use the UI, then the configuration of the Zones is saved as
```
"zones": [
{
  "name" My room ",
  "zone": "[[24650.26717.30200, 30517.1]]"
}
```
And in the description zone (manual) goes without quotes! At the same time, if I manually remove the quotes in the Homebridge configuration, then the coordinates disappear in the UI.
Who is right?

------- Russian ------
Добрый день!

В общем обнаружил ошибку в конфигураторе. Если использовать UI, то конфигурация Зон сохранятеся как 
```
"zones": [
{
  "name" My room ",
  "zone": "[[24650.26717.30200, 30517.1]]"
}
```
А в описании zone идет без ковычек! При этом, если я вручную убираю ковычки в конфигурации Homebridge, то координаты пропадают в UI.
Кто прав?)

**Comment by afharo** [comment]
Hi! Thank you for reporting this issue! 
It should be fixed in `homebridge-xiaomi-roborock-vacuum@0.11.7` :)

**Comment by afharo** [comment]
Sorry! Reopening! Not fixed yet

**Comment by afharo** [comment]
Now it's fixed :) `homebridge-xiaomi-roborock-vacuum@0.11.8`
