### ISSUE TITLE
Apply for Homebridge Verified status

### ISSUE THREAD

**Issue by afharo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#219]
The list of tasks to do are in https://github.com/homebridge/verified

I'm sure we'll learn a lot from it.

**Comment by mitch7391** [comment]
I would be keen to see this one :) how is the progress going to meet the required conditions?

**Comment by afharo** [comment]
I just read through the requirements and it seems like this module ticks all of them.
The only one that I'm not sure about what they actually mean with

> - The plugin must not start unless it is configured.

I've created the verification request anyway at https://github.com/homebridge/verified/issues/113. Hopefully the team will help us with identifying any missing bits :)

**Comment by mitch7391** [comment]
I assume that means the plug-in should not fire up unless it has a 'config' placed in the config.json file? I find they are normally very helpful :) thanks for the update!

**Comment by afharo** [comment]
Approved!! 🚀 

<img alt="Screen Shot 2020-08-03 at 8 47 20 AM" width="708" src="https://user-images.githubusercontent.com/9875439/89189773-14c42200-d566-11ea-8ea6-788cd5e66742.png">

**Comment by mitch7391** [comment]
Nice work! :)
