### ISSUE TITLE
miio issue

### ISSUE THREAD

**Issue by niou-ns** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#222]
Hey there!
I've tried to update the plugin to latest version and it failed.

`EEXIST: file already exists, symlink '../lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/cli/index.js' -> '/usr/bin/miio'`

First package which I've installed with miio was homebridge-mi-air-purifier.
I can remove symlink etc., fix this install issue by myself, but it would be great for community if you would move your version of miio as separate repo (as before) - since original miio is not maintenaned anymore, I think community could work on that. I've got one update for miio too.
Think about that :-) Thanks for your hard work!

**Comment by martonky** [comment]
The same problem. Please, how can I fix that? Nice job anyway. :)

**Comment by niou-ns** [comment]
Just remove /usr/bin/miio - it’s just a symlink.

**Comment by martonky** [comment]
> Just remove /usr/bin/miio - it’s just a symlink.
> […](#)
> Wiadomość napisana przez martonky ***@***.***> w dniu 21.06.2020, o godz. 11:53: ﻿ The same problem. Please, how can I fix that? Nice job anyway. :) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

It works! thank you so much. :)

**Comment by afharo** [comment]
It should be fixed by the version [0.12.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.12.0)
