### ISSUE TITLE
gyp ERR!

### ISSUE THREAD

**Issue by diwiesign** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#225]
If I install the latest version (coming from 0.7.6)with
 
`sudo -E -n npm -g install homebridge-xiaomi-roborock-vacuum@latest --force`

--force because #213 

I always get 

`npm WARN using --force I sure hope you know what you are doing.
/usr/local/bin/miio -> /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/cli/index.js

> deasync@0.1.20 install /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync
> node ./build.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/home/pi/.cache/node-gyp/12.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync/.node-gyp'
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Build failed
+ homebridge-xiaomi-roborock-vacuum@0.11.9
added 124 packages from 103 contributors in 31.5s`

Maybe someone can kindly help me so that I can install updates normally again in the future? Many thanks in advance.

**Comment by afharo** [comment]
I'll rename the binary so it doesn't crash with those using the original `miio` library for other components

**Comment by afharo** [comment]
It should be fixed by the version [0.12.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.12.0)
