### ISSUE TITLE
Add support for Xiaomi Mijia STYJ02YM (viomi.vacuum.v7)

### ISSUE THREAD

**Issue by dnks23** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#226]
May it be possible to add support for the new Xiaomi Vacuum Mop Pro (STYJ02YM) ?

**Comment by Bene2103** [comment]
It has been already done, take a look here

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/216

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/100

**Comment by dnks23** [comment]
why do i then get the following error:

`[6/5/2020, 9:22:00 AM] [Xiaomi-Mi-Vacuum-Mop-Pro] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}`

**Comment by Bene2103** [comment]
Looks like you‘ve got it working?

Maybe you can post your solution for others users with the same problem?

Thanks!
