### ISSUE TITLE
Reduce amount of logs? 

### ISSUE THREAD

**Issue by koles0ff** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#230]
Hello,

please advise, how I can reduce amount of logs? Currently 98% of all HB logs related to Vacuum cleaner.
![image](https://user-images.githubusercontent.com/45538273/84165098-f0732a00-aa7b-11ea-99eb-aff039ca5178.png)

**Comment by afharo** [comment]
Maybe we can add a `silent` option that will avoid logging those status log entries?

It's interesting to me though: those `INF getX` logs are supposed to be shown only when Homekit is requesting those values or trying to set them. Seeing those entries repeated so often seems like Homekit is requesting them too often 🤔 

In other words: it shouldn't log that much when the app is closed, only when there is any activity going on. But still, we can add that `silent` flag if needed.

**Comment by koles0ff** [comment]
The silent option would be very useful for all plugins, thanks! And logs type selection option would be even better. Some check-boxes for "info", "errors", "warnings", etc.

**Comment by afharo** [comment]
I just published 0.14.0 to add a silent configuration parameter that will only show warning and error logs (hiding all info and debug messages).

**Comment by koles0ff** [comment]
Thank you so much! What a relief now :) I have bow only ~10 log messages per minute, instead of 200+.
💯
