### ISSUE TITLE
Roborock S6 MaxV | Model report 106% FanSpeed

### ISSUE THREAD

**Issue by L-C-P** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#235]
S6 MaxV is reporting some not so important warnings in the log. I only got the 106% while chargingthe S6:

[2020-6-22 13:15:47] [S6] MON changedSpeed | roborock.vacuum.a10 | FanSpeed is now 106%
[2020-6-22 13:15:47] [S6] WAR changedSpeed | roborock.vacuum.a10 | Speed was changed to 106%, this speed is not supported

please let me know if you need futher information

**Comment by L-C-P** [comment]
The problem is related to the missing mapping for the new model in models.js.

// S6 MaxV
  "roborock.vacuum.a10": [
    { speed: speedmodes["gen4+custom"], waterspeed: watermodes.gen1 },
  ],

I will add and test the support.

**Comment by afharo** [comment]
It should be fixed by the version [0.12.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.12.0)
