### ISSUE TITLE
Token Invalid issue

### ISSUE THREAD

**Issue by joerexlo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#237]
I followed the instructions and got the token. Here is that i did on high level.

* removed the robot from the mi home app ios.
* reset the wifi.
* I connected my mac mini to the robot wifi.
* used Miio discover command
* noted the result.
* disconnected the robot.
* connected it to the mi home app.
* check if its working no issues with the mi home app.

Homebridge on load still throws the error token invalid. my robot is a Xiaomi mi s1 i got shipped from china since its not available in USA.

any help here?

**Comment by afharo** [comment]
> * disconnected the robot.
> 
> * connected it to the mi home app.

This is the problem: The moment to re-connect the robot to a new app, a new token is issued, revoking any other one. I'd suggest you to use the backup method to retrieve the token. I think it's the most reliable one.

**Comment by joerexlo** [comment]
Thanks for the quick reply. can you help with the right link. there are too many just don't want to get confused.

**Comment by afharo** [comment]
This is the one that worked for me: https://python-miio.readthedocs.io/en/latest/discovery.html#tokens-from-backups :)

**Comment by joerexlo** [comment]
thanks all i got this working. now great appreciate all the help
