### ISSUE TITLE
Xiaomi App modesetting update is wrong, if only fan speed or water speed is changed from custom to fixed value or vice versa

### ISSUE THREAD

**Issue by L-C-P** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#238]
If only one setting is changed, the Xiaomi app is showing inconsistent values in the mode setting.

**Comment by afharo** [comment]
Can you provide more details? I don't entirely understand what this request is about.

**Comment by L-C-P** [comment]
Sorry for the German screenshot. But it explain the problem. Form the app it is possible to activate the custom mode.

![IMG_5975](https://user-images.githubusercontent.com/344139/85883815-e07c7980-b7e1-11ea-8d11-7341d99546e8.PNG)

Or deactivate it. Then the fan speed and water speed can be set.

![IMG_5976](https://user-images.githubusercontent.com/344139/85883817-e2463d00-b7e1-11ea-882e-a5e24ecef574.PNG)

Activate custom mode in Xiaomi app and then set the fan speed mode to 50% in homebridge, the state of the water speed is undefined for the Xiaomi app. Same if I set water and fan to 50% in Xiaomi App and then the fan speed to custom in homebridge. 

![IMG_5977](https://user-images.githubusercontent.com/344139/85883820-e4100080-b7e1-11ea-891f-148296dc1b86.PNG)

The Xiaomi App will always show the fan and the water state. It's not possible to see only one of them.

I already fixed this with the S6 MaxV pr.

**Comment by afharo** [comment]
Cool! Thanks! Looking forward to see the PR :)

**Comment by L-C-P** [comment]
Is it possible that I am not allowed to create a new branch? I always get 403 with git push. I also can not see the create branch button in the web browser?

**Comment by afharo** [comment]
Yeah, that's the usual way to go: https://help.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by L-C-P** [comment]
Thank you for pointing me in the right direction. First PR on git. For business I'm always on MS DevOps.

**Comment by L-C-P** [comment]
Can you provide me a .editorconfig for the formatting rules please?

**Comment by afharo** [comment]
It should be fixed by the version [0.12.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.12.0) (thanks to you! 🚀 )
