### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by roquai23** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#239]
Hi! Facing some problems to install the plugin with the following err!:

![image](https://user-images.githubusercontent.com/65160899/85887506-02352b00-b7f9-11ea-8a1d-020fdeeee342.png)
please advise, what I'm doing wrongly in it.
Thank you in advance.

**Comment by L-C-P** [comment]
Some files are already installed. Maybe from the miso command line? You can try to run your npm install command again and add --force at the end. But you have to check if you really like to override you existing files.

**Comment by roquai23** [comment]
Thank you, —force helped!
