### ISSUE TITLE
Roborock finishes clean but doesn’t return to dock

### ISSUE THREAD

**Issue by JonoHaysom** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#241]
As the title says. The roborock finishes its cleaning and then just stays in its last spot where it finished. It no longer even says “going back To the dock”. Just sits there until it runs out of battery.

**Comment by L-C-P** [comment]
Just had a similar problem. If you run the stop comment a 2nd time, is he returning to the dock? Can you see any error messages in the Homebridge log?

**Comment by JonoHaysom** [comment]
> Just had a similar problem. If you run the stop comment a 2nd time, is he returning to the dock? Can you see any error messages in the Homebridge log?

Nope, I have to go find him and then press the charge button to force him to return. very off, I dont believe there has been a new firmware update thats changing the behaviour when a clean session ends. 

anyone else having the issue?

**Comment by afharo** [comment]
What model do you have, @JonoHaysom?

Can you run `homebridge` with the environment variables `DEBUG="miio:*,thing:*"` and provide the logs you get? This will help us understand what are the internal messages and errors returned by the vacuum? Thank you!

Also, I recall there was an issue with the way iOS13 presented the vacuum and the pause button. If you have only 1 tile grouping all the switches for this vacuum, iOS sometimes mixes the Off signal and the Pause signal itself.

**Comment by JonoHaysom** [comment]
> What model do you have, @JonoHaysom?
> 
> Can you run `homebridge` with the environment variables `DEBUG="miio:*,thing:*"` and provide the logs you get? This will help us understand what are the internal messages and errors returned by the vacuum? Thank you!
> 
> Also, I recall there was an issue with the way iOS13 presented the vacuum and the pause button. If you have only 1 tile grouping all the switches for this vacuum, iOS sometimes mixes the Off signal and the Pause signal itself.

Will do. 

just need a few days as im offsite. hope we can crack it

**Comment by JonoHaysom** [comment]
> > What model do you have, @JonoHaysom?
> > Can you run `homebridge` with the environment variables `DEBUG="miio:*,thing:*"` and provide the logs you get? This will help us understand what are the internal messages and errors returned by the vacuum? Thank you!
> > Also, I recall there was an issue with the way iOS13 presented the vacuum and the pause button. If you have only 1 tile grouping all the switches for this vacuum, iOS sometimes mixes the Off signal and the Pause signal itself.
> 
> Will do.
> 
> just need a few days as im offsite. hope we can crack it

ok, so I dont have logs but I can confirm the behaviour occurs when doing a "clean" and the vac automatically returns to charge before completing the house. when it does that and then goes out to complete the vacuuming it finishing but then doesn't return to the dock.

**Comment by afharo** [comment]
Just to make sure I understand: 

1. You trigger a full clean
2. At some point in the middle of the full clean, the vacuum goes to charge (is it due to an out of battery reason or anything else?)
3. Then, somehow, the full clean is resumed and the vacuum goes on with the full clean where it left it earlier.
4. When it's fully done with the clean, it doesn't go back to the dock?

Did I get it right?

**Comment by JonoHaysom** [comment]
Completely correct. its the RoboRock S5 and it goes back to the dock when it hits 20% to charge. everything else is completely correct

**Comment by afharo** [comment]
Got it now! Thanks for explaining! 

I wonder, though, if this is more of an issue with the vacuum cleaner itself (there is no logic in this module to control the battery and send it to charge based on it and then resume the cleaning). Does it happen when you trigger the cleaning via the Xiaomi Mi app?

**Comment by JonoHaysom** [comment]
No, and thats the weird part. with Mi app it doesn't occur. which is odd

**Comment by JonoHaysom** [comment]
behaviour is still there. at east we know the scenario in which it occurs. I wonder if its an initialisation string for the initial request to start the cleaning.. and one of the parameters isn't passed when using home kit upon cleaning completion if its interrupted with a battery charge in between imitation and completion. where it finishes and then rather than return to dock, it remains paused in the place it finished the original cleaning request.

**Comment by afharo** [comment]
Yeah... that's super weird! It must be related to what you say.

Maybe the debug logs can help us find out what happens and what messages are going through (if run with `DEBUG="miio:*,thing:*"` we should be able to see the underlying messages when talking to the robot).

**Comment by afharo** [comment]
This issue seems stale... I'll close it. Feel free to reopen it when you manage to retrieve the requested logs :)
