### ISSUE TITLE
ERR getState | {"code":"timeout"}

### ISSUE THREAD

**Issue by n00d1e5** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#243]
**I checked the log, the first error message came on June 2nd.**

> [37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | Connected to: 192.168.178.39
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | Model: roborock.vacuum.t4
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | State: charging
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | FanSpeed: 102
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | BatteryLevel: 100
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mINF getSerialNumber | roborock.vacuum.t4 | Serial Number is R0701S92404457
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | Serialnumber: R0701S92404457
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mINF getFirmware | roborock.vacuum.t4 | Firmwareversion is 3.5.8_0358
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mSTA getDevice | Firmwareversion: 3.5.8_0358
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mINF changedCleaning | roborock.vacuum.t4 | Cleaning is OFF.
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mMON changedCharging | roborock.vacuum.t4 | ChargingState is now true
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mINF changedCharging | roborock.vacuum.t4 | Charging is active
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mMON changedSpeed | roborock.vacuum.t4 | FanSpeed is now 102%
[37m[6/2/2020, 9:52:30 PM] [39m[36m[Roborock T4] [39mINF changedSpeed | roborock.vacuum.t4 | Speed was changed to 102% (Balanced), for HomeKit 50%
[37m[6/2/2020, 9:54:42 PM] [39m[36m[Roborock T4] [39m[31mERR getState | {"code":"timeout"}[39m

On May 22, [37m[5/22/2020, 1:55:21 AM] [39mLoaded plugin: homebridge-xiaomi-roborock-vacuum@0.8.4
No error message, everything works perfectly.

> [37m[6/2/2020, 9:48:53 PM] [39m[33mError loading accessory requested in your config.json at position 2[39m
[37m[6/2/2020, 9:48:53 PM] [39m[31mError: The requested accessory 'XiaomiRoborockVacuum' was not registered by any plugin.[39m
[31m    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)[39m
[31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:346:37[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)[39m
[31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)[39m
[31m    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)[39m
[31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)[39m
[31m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[31m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[37m[6/2/2020, 9:48:53 PM] [39mGot SIGTERM, shutting down Homebridge...

Then, updated on May 23, 

> [0;37m[5/23/2020, 2:24:18 PM] [0m[0;36m[Config][0m Running Command: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest
> [0;37m[5/23/2020, 2:25:05 PM] [0m[0;36m[Config][0m [0;31mCommand failed. Please review log for details.[0m
> But no error message as the title of this issue.

Next updated on June 2nd, 
> [0;37m[6/2/2020, 9:48:42 PM] [0m[0;36m[Config][0m Running Command: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest
> [37m[6/2/2020, 9:48:42 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null

But after the update, I have the following error message:
> [37m[6/2/2020, 9:48:53 PM] [39m[33mError loading accessory requested in your config.json at position 2[39m

> [37m[6/2/2020, 9:48:53 PM] [39m[31mError: The requested accessory 'XiaomiRoborockVacuum' was not registered by any plugin.[39m
> [31m    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)[39m
> [31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:346:37[39m
> [31m    at Array.forEach (<anonymous>)[39m
> [31m    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)[39m
> [31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)[39m
> [31m    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)[39m
> [31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)[39m
> [31m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
> [31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
> [31m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
> [37m[6/2/2020, 9:48:53 PM] [39mGot SIGTERM, shutting down Homebridge...

Then, the log showed I restarted Homebridge several times, and the same error message showed too until it came back to work. But it showed the error message in the beginning of the issue.

And today, I did not use my Rockrobo T4.
At 9:28 PM today, it started the auto self-check(?) as follows:
> [37m[6/28/2020, 9:39:58 PM] [39m[36m[Roborock T4] [39mINF getCleaning | roborock.vacuum.t4 | Cleaning is false
> [37m[6/28/2020, 9:39:58 PM] [39m[36m[Roborock T4] [39mINF getBatteryLow | roborock.vacuum.t4 | Batterylevel is 100%
> [37m[6/28/2020, 9:39:58 PM] [39m[36m[Roborock T4] [39mINF getSpeed | roborock.vacuum.t4 | Fanspeed is 102 over miIO. Converting to HomeKit
> [37m[6/28/2020, 9:39:58 PM] [39m[36m[Roborock T4] [39mINF getSpeed | roborock.vacuum.t4 | Fanspeed is 102 over miIO "Balanced" > HomeKit speed 50%

then in 15 min, at 9:54 PM, it showed the timeout error message with no reason.
> [37m[6/28/2020, 9:54:44 PM] [39m[36m[Roborock T4] [39m[31mERR getState | {"code":"timeout"}[39m

If you need any further information, please let me know.

**Comment by n00d1e5** [comment]
"name": "Roborock T4",
            "ip": "192.168.178.39",
            "token": "xxx",
            "waterBox": false,
            "pause": false,
            "dock": false,
            "delay": false,
            "cleanword": "clean",
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"

**Comment by afharo** [comment]
The error you showed when updating
```
[0;37m[5/23/2020, 2:24:18 PM] �[0m�[0;36m[Config]�[0m Running Command: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest
```

It should be gone with the latest release (0.12.0). Can you try again and let me know?

**Comment by n00d1e5** [comment]
I updated to 0.12.0 from 0.11.9 and restarted 
> [6/29/2020, 9:27:11 PM] [Config] Running Command: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest
> [6/29/2020, 9:28:07 PM] [Config] Homebridge restart request received

During the initialization, everything is okay.

> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | Connected to: 192.168.178.39
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | Model: roborock.vacuum.t4
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | State: charging
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | FanSpeed: 102
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | BatteryLevel: 100
> [6/29/2020, 9:28:23 PM] [Roborock T4] INF getSerialNumber | roborock.vacuum.t4 | Serial Number is R0701S92404457
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | Serialnumber: R0701S92404457
> [6/29/2020, 9:28:23 PM] [Roborock T4] INF getFirmware | roborock.vacuum.t4 | Firmwareversion is 3.5.8_0358
> [6/29/2020, 9:28:23 PM] [Roborock T4] STA getDevice | Firmwareversion: 3.5.8_0358
> [6/29/2020, 9:28:23 PM] [Roborock T4] INF changedCleaning | roborock.vacuum.t4 | Cleaning is OFF.
> [6/29/2020, 9:28:23 PM] [Roborock T4] MON changedCharging | roborock.vacuum.t4 | ChargingState is now true
> [6/29/2020, 9:28:23 PM] [Roborock T4] INF changedCharging | roborock.vacuum.t4 | Charging is active
> [6/29/2020, 9:28:23 PM] [Roborock T4] MON changedSpeed | roborock.vacuum.t4 | FanSpeed is now 102%
> [6/29/2020, 9:28:23 PM] [Roborock T4] INF changedSpeed | roborock.vacuum.t4 | Speed was changed to 102% (Balanced), for HomeKit 50%

However, in about 30 minutes, timeout error came again (twice):
> [6/29/2020, 9:54:35 PM] [Roborock T4] ERR getState | {"code":"timeout"}
> [6/29/2020, 9:55:05 PM] [Roborock T4] ERR getState | {"code":"timeout"}

I did not use or touch my robot since the update.

**Comment by n00d1e5** [comment]
Homebridge 1.1.1
plugin list:
- Homebridge Config UI X 4.23.2
- Homebridge Camera FFmpeg 2.0.1
- Homebridge Mi Led Desk Lamp 1.2.0
- Homebridge Raspberrypi Temperature 0.0.7
- Homebridge Xiaomi Roborock Vacuum 0.12.0

**Comment by n00d1e5** [comment]
Well, once I turned the debug mode on, I found that there is communication every 30 seconds, that's a lot in the log. 
> [6/30/2020, 6:27:53 AM] [Roborock T4] DEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.
> [6/30/2020, 6:27:53 AM] [Roborock T4] DEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}
> [6/30/2020, 6:27:53 AM] [Roborock T4] DEB changedBattery | roborock.vacuum.t4 | BatteryLevel 100%
> [6/30/2020, 6:28:22 AM] [RaspberryPi] update currentTemperatureCharacteristic value: 57.996
> [6/30/2020, 6:28:23 AM] [Roborock T4] DEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.
> [6/30/2020, 6:28:23 AM] [Roborock T4] DEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}
> [6/30/2020, 6:28:23 AM] [Roborock T4] DEB changedBattery | roborock.vacuum.t4 | BatteryLevel 100%
> [6/30/2020, 6:28:53 AM] [Roborock T4] DEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.
> [6/30/2020, 6:28:53 AM] [Roborock T4] DEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}
> [6/30/2020, 6:28:53 AM] [Roborock T4] DEB changedBattery | roborock.vacuum.t4 | BatteryLevel 100%

As you can see, there was timeout error even I updated to 0.12.0. However, from 2:39:23 AM to 6:28:53 AM, there is no timeout record. The timeout error is random for me, maybe you have idea about that?

**Comment by afharo** [comment]
You are right! We poll the updates every 30s to ensure we have the latest status.

On top of the `-D` flag, can you set the environment variable `DEBUG=thing:*` to see the underlying communication messages between `homebridge` and the robot?

I'm interested in the logs when that `ERR getState | {"code":"timeout"}` starts to occur.

**Comment by n00d1e5** [comment]
I just back home, here's a full log with two timeout inside.
But so wired...
https://gist.github.com/n00d1e5/0cbda83e19ac13d6131ad8b2e2d6b401

**Comment by afharo** [comment]
I can see it self-recovered, right?

```
...
[37m[6/30/2020, 9:53:56 PM] [39m[36m[Roborock T4] [39m[90mDEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.[39m
[37m[6/30/2020, 9:53:56 PM] [39m[36m[Roborock T4] [39m[90mDEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}[39m
...
[37m[6/30/2020, 9:54:26 PM] [39m[36m[Roborock T4] [39m[90mDEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.[39m
[37m[6/30/2020, 9:54:38 PM] [39m[36m[Roborock T4] [39m[31mERR getState | {"code":"timeout"}[39m
[37m[6/30/2020, 9:54:56 PM] [39m[36m[Roborock T4] [39m[90mDEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.[39m
[37m[6/30/2020, 9:55:08 PM] [39m[36m[Roborock T4] [39m[31mERR getState | {"code":"timeout"}[39m
...
[37m[6/30/2020, 9:55:26 PM] [39m[36m[Roborock T4] [39m[90mDEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.[39m
[37m[6/30/2020, 9:55:26 PM] [39m[36m[Roborock T4] [39m[90mDEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}[39m
...
[37m[6/30/2020, 9:55:56 PM] [39m[36m[Roborock T4] [39m[90mDEB ensureDevice | roborock.vacuum.t4 | The socket is still on. Reusing it.[39m
[37m[6/30/2020, 9:55:56 PM] [39m[36m[Roborock T4] [39m[90mDEB getState | roborock.vacuum.t4 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":102} | Props {"state":"charging","batteryLevel":100,"cleanTime":1709,"cleanArea":27.615,"fanSpeed":102,"in_cleaning":0,"mainBrushWorkTime":120761,"sideBrushWorkTime":120761,"filterWorkTime":120761,"sensorDirtyTime":120569}[39m
...
```

Maybe a faulty connection?

I can see the `ensureDevice` lines consistently running every 30s, but when the `getState | {"code":"timeout"}` shows up, they occur after 12s. 

Instead, when it works, it pretty much gets the response in the same second (the timestamp in `ensureDevice` and `getState` lines are the same).

**Comment by gjanos89** [comment]
Hi!
I also have a very similar issue, don't want to open a new one.
I just recently purchased a Mi Robot Vacuum-Mop version. All goes well and connects, but plugin cannot read then the Serial Nr and get the status, so all HomeKit accessories are offline.

Here is my log content from the connection onwards:

[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | Connected to: 192.168.89.34
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | Model: dreame.vacuum.mc1808
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | State: undefined
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | FanSpeed: undefined
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | BatteryLevel: undefined
[9/1/2020, 1:09:33 PM] [Monica] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[9/1/2020, 1:09:33 PM] [Monica] STA getDevice | Serialnumber: Unknown
[9/1/2020, 1:09:33 PM] [Monica] INF getFirmware | dreame.vacuum.mc1808 | Firmwareversion is 3.5.8_1059
[9/1/2020, 1:09:33 PM] [Monica] STA getDevice | Firmwareversion: 3.5.8_1059
[9/1/2020, 1:09:45 PM] [Monica] ERR getState | {"code":"timeout"}
[9/1/2020, 1:10:27 PM] [Monica] ERR getState | {"code":"timeout"}
[9/1/2020, 1:10:57 PM] [Monica] ERR getState | {"code":"timeout"}

**Comment by gjanos89** [comment]
I understand that, but for me there is no normal operation after this.

**Comment by afharo** [comment]
> I understand that, but for me there is no normal operation after this.

@gjanos89 can you join the discussion on #444. I want to get to the bottom of this :)
