### ISSUE TITLE
Failed getting the cleaning status

### ISSUE THREAD

**Issue by 0Bu** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#248]
Hi. Looks like the new firmware 3.6.8_0.862 on Roborock S5 Max causes errors.

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/22e6bd5bc7d757c29470599b5c48462c66156905/index.js#L800

```
homebridge    | [7/10/2020, 4:22:45 PM] [Roborock EG] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
homebridge    |     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
homebridge    |     at XiaomiRoborockVacuum.getCleaning (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
homebridge    |     at /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:49
homebridge    |     at module.exports (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
homebridge    |     at On.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:26)
homebridge    |     at On.emit (events.js:315:20)
homebridge    |     at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
homebridge    |     at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:488:12)
homebridge    |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
homebridge    |     at Array.forEach (<anonymous>)
homebridge    |     at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)homebridge    |     at HAPServer.emit (events.js:315:20)
homebridge    |     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
homebridge    |     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
homebridge    |     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
homebridge    |     at IncomingMessage.emit (events.js:315:20)
homebridge    |     at endReadableNT (_stream_readable.js:1221:12)
homebridge    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by josemunozmatos** [comment]
Im getting errors too:
7/10/2020, 4:57:05 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
7/10/2020, 4:59:07 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
7/10/2020, 5:00:00 PM [Morning State] Setting switch to false
7/10/2020, 5:01:09 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
7/10/2020, 5:03:11 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
7/10/2020, 5:05:13 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
7/10/2020, 5:07:15 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

**Comment by 0Bu** [comment]
As it looks, the error only appears when the _Roborock S5 Max_ is cleaning up. Once the Roborock S5 Max has parked, the error no longer appears. I have the _Roborock S6_ too with the firmware version _3.5.8_1708_ - no errors.

**Comment by vtl3004** [comment]
Same issue on the xiaomi vacuum cleaner v1

`ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
    at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
    at XiaomiRoborockVacuum.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
    at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1001:49
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
    at On.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1001:26)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)`

**Comment by afharo** [comment]
Hi y'all! Thank you for taking the time to share your logs!

The error described looks to me like this module cannot connect to the vacuum cleaner.

```
ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null at XiaomiRoborockVacuum.get isCleaning [as isCleaning]
```

As pointed out in the description, it comes from the `this.device.property('...')` method. It cannot read `property` of `this.device` when its value is `null`. `this.device` will be assigned to the actual device once the connection happens. I've created https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/251 to hide those errors when this is the case, so we don't come to wrong conclusions. It will be included in the next release.

```
 7/10/2020, 4:57:05 PM [Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
```

Is related to the same issue: the module cannot connect to the vacuum cleaner.

Maybe the token has been regenerated after the upgrade and needs to be fetched again? 

> As it looks, the error only appears when the _Roborock S5 Max_ is cleaning up.

@0Bu That's interesting... maybe the vacuum is reaching some points in the house where it loses the wifi connection?

**Comment by 0Bu** [comment]
Hm. I can no longer reproduce the error. Maybe the Roborock S5 Max just has the hiccups. The ticket can be closed, IMO.

**Comment by vtl3004** [comment]
@afharo 0.12.2 fixed this issue, thanks!

**Comment by afharo** [comment]
Thank you both for confirming! Closing the issue for now!
