### ISSUE TITLE
Watertank is always reported as on

### ISSUE THREAD

**Issue by L-C-P** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#255]
So the vent animation is always on

![IMG_0045](https://user-images.githubusercontent.com/344139/87806247-da187500-c856-11ea-8d0a-f46d613d2806.png)

Fixed in Pull #249

**Comment by afharo** [comment]
It should be fixed in `0.13.0` (thank you!)
