### ISSUE TITLE
ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by Mikellas** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#261]
Hi again,

I changed apps from Mi HOme to ROborock
When changed to Roborock the app said that i had an update to my S6
I  did that restarted and now i get the above error when trying to view in HOME

Can someone assist?It was ok with MiHome

**Comment by afharo** [comment]
Hi @Mikellas, 
When switching between apps (or even resetting the wifi connection), a new token is reissued and the previous one is invalidated. You'll need to retrieve the token again.

**Comment by Mikellas** [comment]
HI Alejandro and thanks for replying
I just figured that out myself!On another note do you happen to know if its possible to extract token from Roborock app specificaly?

Thanks again

**Comment by afharo** [comment]
sorry, I use the Xiaomi Mi app. I was hoping someone would answer in the Roborock app issue if they find a way (personally, I haven't tried).

**Comment by afharo** [comment]
Since you mentioned you figured out. I'll close the issue. Feel free to reopen it if you think it should remain open.
