### ISSUE TITLE
how to define zones without Xiaiomi App / import from Valetudo possible?

### ISSUE THREAD

**Issue by aebgit** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#264]
My S5 runs a modified firmware (FW 002008) with [Valetudo](https://github.com/Hypfer/Valetudo) (v 0.6.1) installed. This way my vacuum runs completely local, without any cloud-connections. 
I want to use the zones-feature in homebridge-xiaomi-roborock-vacuum but am somehow stuck. I have no idea how to start defining zones. Could you give me a push in the right direction?

I tried to use the coordinates sent by Valtudeo (extracted from the API request of the Valtudo WebGUI) but they seem to be incompatible (four instead of 5 digits per coordinate).

Any ideas / suggestions?

Thanks in advance
Andreas

**Comment by afharo** [comment]
Hi! I've never used Valetudo, but I hope I can help you with this.

> (four instead of 5 digits per coordinate)

By 4 digits per coordinate, do you mean `(x1, y1, x2, y2)`?

If so, our 5th coordinate is the number of repetitions in that zone:

- (x1, y1, x2, y2, 5) will clean that zone 5 times before moving to the next one or finishing :)

**Comment by aebgit** [comment]
@afharo Thanks for your help!
No, I meant the number of digits in each position - but nevermind. I already got the confirmation from the Valetudo-team (thanks to @Hypfer) that they're using a private coordinate-system. So it seems to be impossible to use that as a source for my zones-definition.

Any other suggestions on how to start defining zones without the Xiaiomi App? 
- is the dock always in the center of the coordinate-system? (meaning 0,0,0,0)
- are there typical values for how many clicks make a meter?

**Comment by Hypfer** [comment]
You can (and should) define them in Valetudo and just call them by name

**Comment by afharo** [comment]
We should def improve our zones-definition documentation. Here are some hints from the fork we got some hints about how to implement it: https://github.com/Smileydude/homebridge-xiaomi-roborock-vacuum#config-overview

**Comment by afharo** [comment]
This issue has been stale for a while... I'll go ahead and close it. Feel free to reopen it if you think something is still pending.
