### ISSUE TITLE
Room Cleaning: Better action and status control

### ISSUE THREAD

**Issue by Mikellas** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#266]
The current room behaviour is: we can only clean 1 room at a time + when cleaning is on (no matter is general or room-specific, all rooms are enabled as cleaning).

Let's fix it so:

- [x] We correctly report what room/rooms are actually being cleaned
- [x] We allow switching multiple switches ON and all the _ON_ rooms will be cleaned.

-------

# Original description

Hi,
When assigning a specific room to be cleaned in Home app all rooms are highlighted.

Image below
![8D98A7F0-3696-4D0C-9770-BBD164F92ACE](https://user-images.githubusercontent.com/62306024/89423714-87d4c080-d73f-11ea-8154-26b5884abfae.png)

**Comment by afharo** [comment]
@Mikellas thank you for creating this issue! 

We've had previous discussions about this and plan to fix it when we implement the discussion started in #132 (comment) (and follow up comments): Basically, the user will switch ON the rooms to be cleaned and, then, trigger the clean by starting the cleaning. If no rooms are switched ON, we'll trigger a general cleaning (or maybe we can do it so it starts as we switch the room ON, but it waits for a couple of seconds and/or self-correct to make sure the user has enough time to enable all the switches :) ).

Let's use this issue to track that improvement.

**Comment by timothy-morph** [comment]
Can't wait to see this got implemented! 😃
Just had an ideal, is it possible to add one more slider or switch for setting the repetition of cleaning?
Maybe the process then will be like:
- select the rooms that need to be cleaned **and set how many times it will repeat (default to 1 if not set)**
- hit clean

**Comment by bz101** [comment]
I'm sure I'm doing something wrong.  I have an S6 Pure and have tried everything to get the "autoroom" to work (automatic and semi-).  I get the switches in Homekit only when going the semi-auto way.  But flipping the switches does nothing -- it immediately flips back to off. I'd use "rooms" array, but don't know the IDs.  Are there instructions on how the switches should work?  Any way to get Siri to trigger?  Thx!

**Comment by afharo** [comment]
@bz101 I think your question was answered in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/267, right? 🙂

**Comment by bz101** [comment]
Yes, it was!!  TY!

**Comment by MAnjemark** [comment]
Hi! Any update on the progress so far! Thanks! @Mikellas

**Comment by afharo** [comment]
I think I'll have some spare time this month to work on some improvements in this plugin. I'll take on these improvements soon enough :)

**Comment by sorriso93** [comment]
Hello frankly speaking I preferred the old version, it is better to use it with siri (siri clean kitchen for example). Is it possible to have the possibility to use the old behavior?

**Comment by afharo** [comment]
Hi @sorriso93, in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/326, we've added a way to allow both: multiple-room cleaning + auto-start when a room is enabled.

Just set the option `roomTimeout: 5` (where 5 is the number of seconds you want the plugin to wait before start the cleaning). We thought of this approach to allow users to navigate through the app and reach multiple rooms in case they want to enable it. It is disabled by default (its default config value is `0`), but we might consider adding it by default in future versions if the users prefer it this way.

I think it's worth adding a more extended explanation in the README.

**Comment by afharo** [comment]
Closing this issue, since it looks like its original description has been achieved :)

**Comment by sorriso93** [comment]
> Hi @sorriso93, in #326, we've added a way to allow both: multiple-room cleaning + auto-start when a room is enabled.
> 
> Just set the option `roomTimeout: 5` (where 5 is the number of seconds you want the plugin to wait before start the cleaning). We thought of this approach to allow users to navigate through the app and reach multiple rooms in case they want to enable it. It is disabled by default (its default config value is `0`), but we might consider adding it by default in future versions if the users prefer it this way.
> 
> I think it's worth adding a more extended explanation in the README.

Thanks I didnt't get in the instructions on home page, I double checked before posting.

**Comment by afharo** [comment]
Yeah... sorry, I added them after posting the comment for future reference: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#room-cleaning

It was not there when you initially approached us :)
