### ISSUE TITLE
Room cleaning switches don’t appear in HomeKit

### ISSUE THREAD

**Issue by KayGundhardt** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#268]
Hi there,

I think I followed the explanations step by step to add the rooms but they simply don’t appear in HomeKit. I’ll send you a status screenshot...

Thank you for your help!

Kay 
![4D634071-E03E-48F0-B400-798BA3C1D531](https://user-images.githubusercontent.com/69385168/89720898-7279c380-d9d7-11ea-9927-121958558945.jpeg)

**Comment by KayGundhardt** [comment]
On the other hand side, that HAP warning on the screenshot has maybe nothing to do with the missing room cleaning switches?

**Comment by afharo** [comment]
Hi @KayGundhardt, you are correct about the HAP warnings. They are related to something else (#257).

Can you share your config (obscuring the IP and token) so I can try to troubleshoot?

**Comment by KayGundhardt** [comment]
Hey Haro,

Thank you very much for your offer to help! :)

Here comes the config:

{
    "bridge": {
        "name": "Homebridge 9C0A",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxx,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [
        {
            "name": "Untergeschossesauger",
            "ip": "xxx",
            "token": "xxx",
            "waterBox": false,
            "pause": true,
            "pauseWord": "pause",
            "findMe": true,
            "findMeWord": "finden",
            "dock": true,
            "delay": false,
            "cleanword": "reinigen",
            "autoroom": true,
            "rooms": [
                {
                    "name": "Wohnzimmer Nord",
                    "id": 1
                },
                {
                    "name": "Wohnzimmer Süd",
                    "id": 2
                },
                {
                    "name": "Esszimmer",
                    "id": 3
                },
                {
                    "name": "Küche",
                    "id": 4
                },
                {
                    "name": "Hauseingang",
                    "id": 5
                },
                {
                    "name": "Toilette",
                    "id": 6
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        }
    ]
}

Greetings!!


Kay

**Comment by afharo** [comment]
oh! I see what's happening! You can't use "autoroom" and "rooms" at the same time.

If you can use `"autoroom":true` for fully automated room discovery (only models that allow you to name the rooms in the Xiaomi Mi Home app support this feature).
Or use the `"autoroom": ["Room A", "Room B", "Room C"]` for the timer-driven semi-automatic approach.

Both of them will return the "rooms" array in the logs, copy it and add it to the config and don't forget to remove "autoroom" from it.

**Comment by afharo** [comment]
I've added a validation step in `0.13.4` to remind folks about these 2 fields are incompatible (#270)

**Comment by KayGundhardt** [comment]
Hey Alejandro,

Thank you very much for your fast and great Help!!! Siri, Roborock and I now do Genie-like Magic cleaning the whole house while I’m sitting on the veranda drinking cocktails! You made a childhood-dream come true... 

:)))


Kay

**Comment by KayGundhardt** [comment]
Hey Alejandro,

Rooms appear now!!! Yippee! :)) But the vacuum cleaner now tries to reach any of the set up rooms and stops immediately saying that he couldn’t reach the specific room. This happens with all rooms...

What am I doing wrong?

:(


Kay

**Comment by afharo** [comment]
Maybe the vacuum cleaner got a glitch in the map... Running a full clean should update the map :)

**Comment by KayGundhardt** [comment]
Hey,

Solved the problem using the semi-automatic method! Only last thing is: when I restart the cleaner after using the HomeKit pause-switch again it does start a new cleaning process (as if it had not cleaned before) instead of continuing the pause cleaning: is this how it should behave?

And a very last thing: THANK YOU VERY MUCH for this really GREAT plugin that finally brings vacuum cleaners to HomeKit in a really SMART way (not only on/off) plus being really RELIABLE and FAST!!! ThxxXXX!!


Kay

**Comment by afharo** [comment]
> Only last thing is: when I restart the cleaner after using the HomeKit pause-switch again it does start a new cleaning process (as if it had not cleaned before) instead of continuing the pause cleaning: is this how it should behave?

It shouldn't, but it's a known bug for now: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/269

Thank you for confirming this has been resolved. I'll proceed to close this issue now. Please, feel free to reopen again it if needed.
