### ISSUE TITLE
Pause not working 

### ISSUE THREAD

**Issue by HennieLP** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#269]
if i clean only the kitchen and then pause and unpause it again it cleans the hole house

**Comment by afharo** [comment]
Hey @HennieLP, thank you for your issue. 

This is what I understand from your description of the issue:

1. You start the cleaning **only for a Room**
2. While cleaning, you hit the **Pause** option
3. When unpausing (hitting the Pause option again), it starts a full cleaning

Is that correct?

**Comment by HennieLP** [comment]
Yes

**Comment by afharo** [comment]
OK! In that case, it's related to #266.

At the moment, we don't have a way to differentiate between room and full cleaning once it's in progress. We have #266 to track the efforts to overcome this limitation.

**Comment by HennieLP** [comment]
Okay thx
