### ISSUE TITLE
Xiaomi Mop Pro

### ISSUE THREAD

**Issue by marithpl** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#272]
Is this plugin compatible with Xiaomi Vacuum Mop Pro?

**Comment by afharo** [comment]
Hi @marithpl, is it the same model as https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/234 ?

**Comment by marithpl** [comment]
I think so

**Comment by afharo** [comment]
I'll close this issue in favor of #234
