### ISSUE TITLE
ERR connect | miio.device, next try ... Error: could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by newmans99** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#275]
Trying to setup my new Roborock S6. I followed the directions to get token, but must have something wrong. 

When I use packet sender, I get the following ASCII response (modified)... 
!1\00 \00\00\00\00\0f\9d\1b\bf\00\01\02\129px0zDb6J3Dr2iCR

I assume it is the last 16 characters starting with 9p...CR, which is what I put in the settings. 

But that doesn’t seem to work and I get the message in the title. 

Any thoughts/recommendations?

**Comment by afharo** [comment]
AFAIK, the tokens are 32-character-long hex-coded strings (only from 0-9 and a-f are valid).

Reading through the [docs in here](https://python-miio.readthedocs.io/en/latest/discovery.html) it claims:

> For some devices (e.g. the vacuum cleaner) the automatic discovery works only before the device has been connected over the app to your local wifi. This does not work starting from firmware version 3.3.9_003077 onwards, in which case the procedure shown in [Tokens from backups](https://python-miio.readthedocs.io/en/latest/discovery.html#creating-backup) has to be used to obtain the token.

**Comment by newmans99** [comment]
Thanks. I was hoping to not use MIHome but use the Roborock app. Unfortunately that will not work, you have to use MIHome and the backup method as mentioned. It is working now, thank you!
