### ISSUE TITLE
How do i find room ID?

### ISSUE THREAD

**Issue by PrimaryInc** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#277]
Hi,

Im wondering how room ID and room name correspond.
I just gave my rooms an ID from 1-7 and named room accordingly to map name. 
BUT when i select say livingroom, it moves to a different room.

I only have Xiaomi Home app on iOS.

Any help would be appreciated.

**Comment by afharo** [comment]
Hey @PrimaryInc,

The IDs are assigned randomly by the vacuum. We've seen them in the range of 10-29 but it varies, depending on the model.

You might want to take a look at the docs: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#autoroom-generation

**Comment by veniplex** [comment]
@PrimaryInc I am facing the same issue. I configured everything over the web-interface. I assigned ID 1-5 for my rooms and according to the instructions I created a timer in the xiaomi app and selected all rooms in the order as mentioned. I use Roborock S5 and I cannot name rooms in the Xiaomi Mi Home App. Also I dont see any room ids.

@afharo Does this mean I have to try & error with IDs between 10-29?

**Comment by PrimaryInc** [comment]
Hi @afharo, @veniplex,

So I did look at the guide. It would be better if it had more example config or pictures to "show" people.
I did enable autoroom, but then I get a error in plugin that autoroom and room cannot be enabled at the same time. So I deleted "room" from plugin UI. But then I rely don't have any room selection in config. 

So I guess that I need to add them manually?
@afharo do you have a configuration example that you can share?

**Comment by veniplex** [comment]
@PrimaryInc As far as I understand you have to:

1. Go to Xiaomi Home App and create a timer at 12:00 am and select rooms. The **order** you select the rooms is important for the plugin.
2. Save the timer and disable it.
3. In the config define e.g.:
`...
"rooms": [
    {
      "id": 16,
      "name": "Livingroom"
    },
    {
      "id": 17,
      "name": "Kitchen"
    }
  ],
...`
4. Restart Homebridge.
5. Now you should be able to select "Clean Livingroom" in the Home App and roborock should clean livingroom. **For me that doesn't work.**

**Comment by PrimaryInc** [comment]
@veniplex, Hi so guide states to enable "autoroom", to me this suggest this option in GUI:
![Screenshot 2020-08-25 at 18 01 49](https://user-images.githubusercontent.com/45151934/91198615-0ef0d500-e6fd-11ea-9f72-5b5206c2b246.png)

This option is not compatible with the "room" section. At least I get an error message stating so:
![Screenshot 2020-08-25 at 18 03 52](https://user-images.githubusercontent.com/45151934/91198805-57a88e00-e6fd-11ea-8c32-3ea68de5f709.png)

Result:
![Screenshot 2020-08-25 at 18 04 24](https://user-images.githubusercontent.com/45151934/91198875-6b53f480-e6fd-11ea-9400-b364e3b24914.png)

Thats why I was hoping to get @afharo to share his config if he has it working :)

I did try the room selection and combining it with the timer but it does not work. 
It is something with the autoroom code that needs to be added and the room code must be removed.

Question is how :)

**Comment by veniplex** [comment]
@PrimaryInc Ok. If you fixed this, please let me know :D..

**Comment by afharo** [comment]
> @PrimaryInc As far as I understand you have to:
> 
>     1. Go to Xiaomi Home App and create a timer at 12:00 am and select rooms. The **order** you select the rooms is important for the plugin.
> 
>     2. Save the timer and disable it.
> 
>     3. In the config define e.g.:
>        `... "rooms": [ { "id": 16, "name": "Livingroom" }, { "id": 17, "name": "Kitchen" }   ], ...`
> 
>     4. Restart Homebridge.
> 
>     5. Now you should be able to select "Clean Livingroom" in the Home App and roborock should clean livingroom. **For me that doesn't work.**

To be clear, the `autoroom` option only helps with the discovery of the room IDs, so you'll need to use it to print in the logs the final `rooms` config and then disable it.

The steps that you mentioned are almost correct.

But in step 3 instead of defining `rooms`, since you don't know them yet, you need to set `"autoroom": ["Livingroom", "Kitchen", ...]` (in here the order needs to match the one in the timer) and nothing at all in the `"rooms"` property (we throw an error when both properties are used together to avoid confusion).

Then, after the restart, you should see printed in the logs the discovered list of rooms with their IDs `[{ "id": 16, "name": "Livingroom" }, ...]`. You can use this information to set the `rooms` options. 

Go back to the config editor, remove the `autoroom` option (or set it to `false`) and set `rooms` based on the info we just retrieved in the previous step. 

You'll need another restart for the plugin to get the new and final config.

At this point you can even delete the timer if you like, the rooms are static now with the right IDs in your `rooms` config.

I hope it makes sense 🙂

**Comment by PrimaryInc** [comment]
@afharo, Ah that makes sense.

Tried 2 things:
1. Enabled autoroom without timer enabled, result:
![Screenshot 2020-08-25 at 18 28 10](https://user-images.githubusercontent.com/45151934/91203115-0a2f1f80-e703-11ea-893c-71493be529e2.png)
ID 16 to 21.

2. Enabled autoroom with timer settings.
![Screenshot 2020-08-25 at 18 41 24](https://user-images.githubusercontent.com/45151934/91203279-3ea2db80-e703-11ea-8cef-94b9edfd62df.png)

Result:
![Screenshot 2020-08-25 at 18 42 18](https://user-images.githubusercontent.com/45151934/91203332-49f60700-e703-11ea-877f-6591e65aa2fd.png)
ID 0-5, roomes named

Removed autoroom config and added rooms again with the corresponding ID and room name. 
![Screenshot 2020-08-25 at 18 49 39](https://user-images.githubusercontent.com/45151934/91203936-bcff7d80-e703-11ea-80d2-f16f861f7de5.png)

So far so good, expect that the ID seems to be a bit off. 0-5 and not 16-21.
And what every I try to start sends S6 out of dock, then returns again. 
If S6 from Xiaomi Home App, I don't get a room ID from logs :(

Could this be a firmware issue?

@veniplex, what firmware does your S6 have?

**Comment by afharo** [comment]
AFAIK, S5 and S6 behave differently. The main difference is the rooms can be named in the application for the S6 model but you can't do so in S5.

I think, for S6, name the rooms in the Xiaomi Home App application and use the [Fully automatic](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#fully-automatic) method (`autoroom: true` instead of the list of names) to print the right names-ID relationships (both, the names and the IDs, obtained from the vacuum).

**Comment by PrimaryInc** [comment]
@afharo, true default config from web ui writes the autoroom: true. 
I've changed configuraton to this:
 {
            "name": "Xiaomi Mi Robot Vaccum",
            "ip": "10.0.x.x",
            "token": "xxxxxxxxxx",
            "waterBox": false,
            "pause": true,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "delay": false,
            "cleanword": "cleaning",
            "autoroom": true,
            "accessory": "XiaomiRoborockVacuum"
        },

Not deleted timer in Xiaomi app and did a restart of homebridge. Log show:
![Roborock 01](https://user-images.githubusercontent.com/45151934/91289456-a81dfb00-e792-11ea-86b8-7c7a88865455.PNG)

As you can see no room name listed. Perhaps I rooms are listed in same order as added to timer. I dont know but I will try it unless other suggestion?

**Comment by veniplex** [comment]
@afharo Thank you mate! It worked for me.

@PrimaryInc Here is my manual :).
My roborock: **S5** with Firmware **3.5.7_002008**

1. Open Homebridge web-interface and log in.
2. Go to Plugins tab and click on Settings for "Homebridge Xiaomi Roborock Vacuum".
3. Scroll down, activate the checkbox for "Automatic Room Detection".
4. Make sure "Rooms" is empty and save.
5. Go to Configuration tab and search under "accessories" the keyword "autoroom".
6. It should be `"autoroom": true,`.
7. Change it to `"autoroom": ["Room1", "Room2", "RoomN"],` and save it.
8. Go to Xiaomi Home App and click on your roborock.
9. Click on the three dots in the uppe right to open the roborock menu and click on "Timer".
10. Create a new timer with "Start: 00:00".
11. Select "Select zones" and then select all rooms **in the exact same order**, you typed in step 7.
12. Save the timer and disable it.
13. Go back to Homebridge web-interface and restart Homebridge.
14. After the restart you will see something like that in the logfiles of Homebridge:
`[Roborock] INF getRoomList | roborock.vacuum.s5 | Created "rooms": [{"id":16,"name":"Room1"},{"id":18,"name":"Room2"},{"id":17,"name":"RoomN"}]`
15. Save those IDs.
16. Go back to the Plugin configuration. "Automatic Room Detection" should now be disabled.
17. Now enter all your rooms with the corresponding ID under "Rooms" and save.
18. Restart Homebridge.
19. Now all rooms should appear in the Home App.

PS: If a room doesn't work, make sure the IDs are correct. E.g. you selected the rooms in the wrong order in the Xiaomi Home App.

I hope it will help :).

**Comment by PrimaryInc** [comment]
@afharo , @veniplex 

So what I did, the room ID 16-21 is correct. I simply ran the S6 manually from HomeKit, and remapped ID to correct room name.
I was not able to list the names from room as suggested in guide or by your guidanse. 

Might be something with S6 and firmware version I have that not output the names when using autoroom config and timer. Doing so shows different room ID that is not mapable via rooms config,

Thanks for helping. Let me know it testing in my environment is wanted for a newer version of plugin 👍

**Comment by veniplex** [comment]
@PrimaryInc Hm sorry to hear that... maybe @afharo can help you with further investigation.

**Comment by PrimaryInc** [comment]
@veniplex , no problem I did get it to work in the end som I'm happy :)

**Comment by veniplex** [comment]
@PrimaryInc Ah ok :D I thought you still have problems to get it working. Good to hear!

**Comment by afharo** [comment]
Thank you both for the confirmation! Why can't Xiaomi make them models to work the same? That's something we'll never know! 😅 

@PrimaryInc One last question about your use case (`autoroom: true`), did you name the rooms in your Xiaomi Home App? I've got a model S5, so can't test the S6 behaviour, but I was told by other folks in S6 you can name the rooms in the app and it will work in the discovery phase (although maybe it got broken on the latest firmware update 🤷 )

**Comment by PrimaryInc** [comment]
Hi @afharo,

Yes, rooms are named in app:
![Screenshot 2020-08-26 at 14 30 38](https://user-images.githubusercontent.com/45151934/91303739-baa32f00-e7a8-11ea-90a9-6201e5ff3a87.png)

So it beats me why I dont get the names mapped as per your guide. If I can assist you in anyway let me know.

Thanks for creating this plugin!! :)

**Comment by afharo** [comment]
Weird! And thank you for your quick feedback! It's great to maintain a plugin with such a great users ❤️

**Comment by datainajar** [comment]
Hello,
- I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
- Located in Australia.
- Using the “Mi Home” App
- In the “Settings” section of the app I do see “timers” instead I see “schedules”
- I’ve removed all “schedules”
- Created a new “scheduled” for “00:00” and selected all the rooms on the map.
- Saved the “schedule”
- Disabled the “schedule”
- Restart home bridge.
- I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.

Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…
![IMG_1491](https://user-images.githubusercontent.com/87596453/130231812-e0823c6f-eafa-4192-ba77-a3d51d336ad3.PNG)
![IMG_1492](https://user-images.githubusercontent.com/87596453/130231822-e4ae02a8-59a2-4c3e-bb37-7e8e5a75f338.PNG)

**Comment by cgmartin** [comment]
I encountered this issue when trying to use miiocli vaccum get_room_mapping method with a roborock.vacuum.s5, where it was returning an empty list of segments.

I used this workaround to get the segment IDs for the room configuration.

ie. my working config:

"accessories": [
        {
            "name": "Xiaomi Mi Robot Vaccum 1st Generation",
            "ip": "192.168.x.x",
            "token": "abcd...",
            "waterBox": false,
            "dustCollection": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "cleanword": "cleaning",
            "roomTimeout": 0,
            "rooms": [
                {
                    "name": "Living Room",
                    "id": 16
                },
                {
                    "name": "Dining Room",
                    "id": 17
                },
                {
                    "name": "Kitchen",
                    "id": 18
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],

**Comment by takenek** [comment]
Hello Guys,
Anyone know how to find room ID for STYJ02YM with 3.5.3_0017 firmware ?

I try both and not show :(

root@radvd:~# miiocli vacuum --ip XX --token XX get_room_mapping
/usr/local/lib/python3.9/dist-packages/miio/click_common.py:270: DeprecationWarning: Call to deprecated function __init__ (This class will become the base class for all vacuum implementations. Use RoborockVacuum to control roborock vacuums.).
  ctx.obj = self.device_class(*args, **kwargs)
Running command get_room_mapping
WARNING:miio.device:Found an unsupported model 'viomi.vacuum.v8' for class 'Vacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
ERROR:miio.miioprotocol:Got error when receiving: timed out
Error: No response from the device

root@radvd:~# miiocli viomivacuum --ip XX --token XX get_rooms
Running command get_rooms
{}

Best Regards
TaKeN

**Comment by adamxfort** [comment]
Hey, I got it working like this
In the MiHome app create a new schedule at 00:00 with all but one room and another schedule at 00:00 with only the remaining room. (disable both of them)
Then run this in cmd line `miiocli viomivacuum --ip your_robot_ip --token your_robot_token get_rooms`
