### ISSUE TITLE
Can't set Water Level to OFF.

### ISSUE THREAD

**Issue by alxalxnet** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#284]
I have a Roborock S5 Max, which has 4 Water Levels (Off, Low, Medium, High). Depending on the fan speed I choose in the Water Box fan accessory, I can change the water level to Low, Medium, or Strong, but if I switch off the Water Box fan or lower its speed to 1% the vacuum will not change the level to OFF.

**Comment by afharo** [comment]
Hey @alxalxnet, 

AFAIK, it should be 0% in order to set it OFF. You can see the different levels we've got setup for that model in here:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/a0be525387ed876aad88ea55849055ad26e480e5/models/watermodes.js#L4-L30

**Comment by alxalxnet** [comment]
Thanks for the prompt reply.
I tried both on my iPhone as well as on my Mac, but I cannot set the Water Box fan 0%—no matter how slow I drag the fan slider down. I can get it to 3%, 2%, 1%, but the next step after that will be OFF, no 0%. Same thing if I tell Siri: "Set the Water Box to 0%." The result is the Water Box fan set to OFF and Siri reply is "OK, the Mop is OFF"

**Comment by afharo** [comment]
And when you start a clean while having the Water Box set to ~0%~ OFF, does it still use the Water Box?

Sorry, I'm not sure I'm understanding the question 🙂

**Comment by alxalxnet** [comment]
Yes, it still uses water (it switches to the "Light" level, instead of "OFF").

1) Original question: How can I set the vacuum to clean a room without mopping (i.e., setting the water level to "Off")?
2) Your answer: Set up up the Water Box fan level to 0%
3) However, Homekit does NOT allow you do set a fan to 0% (only to OFF or 1%)

Could change the percentages in the watermodes.js file to:
Off (25%)
Light (50%)
Medium (70%)
High (100%)

Or, can I change those settings on my end?

**Comment by afharo** [comment]
Published a fix in version `homebridge-xiaomi-roborock-vacuum@0.13.5`.

Instead of changing the percentages (which might break the use of other users), I thought it was better to handle the OFF requests sent by iOS to set the speed to 0%.

Feel free to reopen if, after updating, it doesn't work.
