### ISSUE TITLE
Speed issue for rockrobo.vacuum.v1

### ISSUE THREAD

**Issue by s0n1c** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#296]
The error occurs after each update:

`WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 90%, this speed is not supported`

As in the past it is enough to change .gen2 to .gen1 in /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/models/models.js:

**Error:**
> module.exports = {
>   default: {
>     speed: speedmodes.gen4,
>   },
>   "rockrobo.vacuum.v1": [
>     {
>       speed: speedmodes.gen2,
>     },

**Hotfix:**
> module.exports = {
>   default: {
>     speed: speedmodes.gen4,
>   },
>   "rockrobo.vacuum.v1": [
>     {
>       speed: speedmodes.gen1,
>     },

Can you please solve the error permanently?
Thank you very much for the work, the passion, the time, creativity and enthusiasm for this plugin!

**Comment by afharo** [comment]
Oh! @s0n1c! Thanks for the heads up! I've created https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/302 to make sure the next releases have the right mapping.

**Comment by afharo** [comment]
Published as `homebridge-xiaomi-roborock-vacuum@0.13.6`

**Comment by mpuff** [comment]
i have this same error on a Xiaomi Mi Robot 1S.

**Comment by afharo** [comment]
Can you confirm the model identifier as you see it in the logs (something like `rockrobo.vacuum.v1`)?
Thank you!

**Comment by mpuff** [comment]
[12/27/2021, 9:11:18 PM] [Xiaomi Mi Robot Vaccum 1s] INF getSpeed | roborock.vacuum.m1s | Fanspeed is 104 over miIO. Converting to HomeKit

now I get these message, 104 is ok, the model id looks ok

**Comment by afharo** [comment]
We might need to define the correct mapping of the speeds in the models.js file
