### ISSUE TITLE
Question for using Roborock App

### ISSUE THREAD

**Issue by Kohle81** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#300]
Hi,

thanks for this plugin!! I have get today the Roborock S6 maxV.

I have a question to this part:

Fully automatic

This feature seems to be working on models that support naming the rooms in the Xiaomi / Roborock App. This is known to include the Roborock S6 as well as the S4 with firmware version 3.5.8_0358 or newer.

Even if you have one of these models but you haven't named the Rooms in your App yet, this function will not work! Thanks @domeOo

How can I get the token in Mi Home and using the Roborock App? Is this possible?

**Comment by afharo** [comment]
Hi @Kohle81,

Other folks are trying to make it work with the Roborock App but they haven't found out how to do so yet: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/104 

Apparently the Roborock App has a different way to authenticate the robot, and it invalidates the token every time you use the app 🤷
