### ISSUE TITLE
0.13.6 Homebridge doesn't start

### ISSUE THREAD

**Issue by sergoo-lbt** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#303]
0.13.6 Homebridge doesn't start. I had to roll back to the previous version.
———————————-
Homebridge ver. 1.2.3
Raspberry Pi4, 4Gb

**Comment by afharo** [comment]
Hi @sergoo-lbt 

I'm running the same version myself and it's working fine. What's the error that you get on your end?

**Comment by sergoo-lbt** [comment]
> Hi @sergoo-lbt
> 
> I'm running the same version myself and it's working fine. What's the error that you get on your end?

![Uploading C6FD3FA9-1DB3-4CB9-BC79-00AEA4AF9170.png…]()

**Comment by sergoo-lbt** [comment]
> Hi @sergoo-lbt
> 
> I'm running the same version myself and it's working fine. What's the error that you get on your end?

![C9309CFF-5C56-4652-A125-DB3EE546C689](https://user-images.githubusercontent.com/64399012/97998816-6487e300-1e0c-11eb-87ba-54fe99196188.png)

**Comment by afharo** [comment]
> With autoroom turned off, everything is fine. When enabled, homebridge does not start.

Oh! Yes! There's a validation where autoroom and rooms cannot be set at the same time. If rooms are set, autoroom shouldn't be set, so the plugin rejects the configuration and fails.

**Comment by sergoo-lbt** [comment]
> > With autoroom turned off, everything is fine. When enabled, homebridge does not start.
> 
> Oh! Yes! There's a validation where autoroom and rooms cannot be set at the same time. If rooms are set, autoroom shouldn't be set, so the plugin rejects the configuration and fails.

I understand! Thanks! Close...
