### ISSUE TITLE
Pin & Go Function

### ISSUE THREAD

**Issue by Kohle81** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#306]
hello, it's me again.  i am enthusiastic about the functions of the plugin.  I came across the pin & go function in the mi home app.  would an integration be possible by specifying the coordinates?  so the roborock could move to a certain place on command, for example to empty the filter in the garbage can or out from under the cupboard to fill the water tank.  It shouldn't be a criticism, but a question as to whether this can be implemented?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by afharo** [comment]
Hi @Kohle81!

Yes! This method makes perfect sense! I think it's related to #130 and #256? Or do you mean something else?

**Comment by Kohle81** [comment]
Hi,

perfect! This is my idea 👍

**Comment by afharo** [comment]
It should be resolved by @luc-ass in version https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.23.0
