### ISSUE TITLE
if you set the turbo or max mode, the message is displayed in the logs every 30 seconds

### ISSUE THREAD

**Issue by Zver5** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#311]
[11/17/2020, 09:10:48] [Пылесос] WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 100%, this speed is not supported undefined
[11/17/2020, 09:11:18] [Пылесос] WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 75%, this speed is not supported undefined
 f you select the standard vacuum cleaner mode there will be no messages in the data logs

**Comment by afharo** [comment]
Hi @Zver5, thank you for sharing this issue. It feels like the mapping of speeds for this model is not entirely correct. Can you share what are all the modes that model has?

- Off
- Standard
- Turbo

Any additional one? Quiet? Mop mode?

**Comment by FTHS92** [comment]
Hello,
I have the same warning, too. "WAR changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 100%, this speed is not supported" It's the first-gen Xiaomi Robot Vacuum Cleaner. It has 4 speed modes in the app (from low to high):
"Silent, Standard, Turbo and MAX" I hope this will help you to fix it.

**Comment by afharo** [comment]
@s0n1c, your suggestion in #296 broke speeds for everyone else. I'm going to revert those changes and we can discuss further what's behaving differently in your model.

**Comment by afharo** [comment]
Published as [v0.16.1](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.16.1)
