### ISSUE TITLE
REQUEST: be abke to move around room specific switches

### ISSUE THREAD

**Issue by BaRaD5** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#318]
Hey!
First of all great plugin! thank you for the time and effort you put in to it!
Something that is really bothersome is the fact that I cant move "room switch" that cleans a specific room
I.E theres a switch that will start to clean my living room but i cant move that switch to the living room because the vacuum "fan switch" is in another room and if i do move it then all the rooms and switches move together as a unit.

If theres a quick fix for this id like to hear, and if not id like this feature added to an already great plugin :)

thank you thank you !

**Comment by afharo** [comment]
Hey @BaRaD5, thank you for the nice words!

The reason for the issue you are describing is that this plugin was developed as a Homebridge Accessory. We're planning on migrating it to behave as a _Platform_. It will allow us to create each room switch as individual accessories. This way, we'll be able to move the switches to other rooms without further issues :)

The issue with those plans is #247.

**Comment by BaRaD5** [comment]
Sounds great! I will be looking forwards for it!
thank you thank you!
