### ISSUE TITLE
I’m getting warnings spam on HB 1.3.0 beta 27 in logs

### ISSUE THREAD

**Issue by njuart** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#320]
Hi, I'm on HB 1.3.0 beta 27. And I see in logs these warnings almost every 30 seconds. Would you mind checking if there's something wrong with it? It keeps spamming. Thx a lot in advance.
![image](https://user-images.githubusercontent.com/21228802/100274232-c1d40780-2f66-11eb-95e8-41191e8ee0f4.jpeg)

**Comment by njuart** [comment]
Hi, any ideas about it? It's still spamming =(

**Comment by afharo** [comment]
I think I might need more context. We have a few characteristic `On`, and after a quick check throughout the code, they all look like they always return a value (or throw an error).

Q: Why are you running `homebridge`'s 1.3.0 beta?

According to their releases https://github.com/homebridge/homebridge/releases/tag/v1.2.4, even 1.2.x is not considered _stable_:

> Notice: This release is tailored towards people already running 1.2.x. As of now 1.1.6 will remain the latest stable version.

**Comment by afharo** [comment]
It should be fixed in the latest versions of the plugin. I'll go ahead and close this issue. Please, feel free to reopen.
