### ISSUE TITLE
no room cleaner from homekit

### ISSUE THREAD

**Issue by giannimp** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#332]
The latest release, the command to clean rooms no longer works!
No clean from ios no clean from alexa I Use hoobs last release
Thank you
![WhatsApp Image 2020-12-04 at 09 05 18](https://user-images.githubusercontent.com/45820952/101138246-3e728000-3610-11eb-8fbd-7a8edcab2236.jpeg)
![WhatsApp Image 2020-12-04 at 09 05 19](https://user-images.githubusercontent.com/45820952/101138249-3f0b1680-3610-11eb-9b43-cd49669fbadb.jpeg)

**Comment by afharo** [comment]
Hi @giannimp, I would recommend you to read the changelog of each release to understand it any improvements/changes affect you :)

In 0.15.0 a new behaviour for Room Cleaning was introduced: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.15.0
In 0.16.0 an additional config parameter was introduced to allow auto-start cleaning when a room is selected: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.16.0

More details about how it works and how to use it, in the new section **Room cleaning** in the README: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#room-cleaning
