### ISSUE TITLE
Room IDs do not work anymore

### ISSUE THREAD

**Issue by Dane03** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#337]
Hi there,

Thanks for your great work on this!

Unfortunely, out of a sudden, room cleaning of dedicated rooms doesn't work anymore since about 1-2 weeks. Before, it worked flawless, now I can only start stop my S5 Max, but the rooms don't work anymore...

Any Tipps?

{
            "accessory": "XiaomiRoborockVacuum",
            "autoroom": false,
            "cleanword": "staubsaugen",
            "delay": false,
            "dock": true,
            "ip": "192.168.178.31",
            "name": "Wall-E",
            "pause": true,
            "rooms": [
                {
                    "id": 16,
                    "name": "Küche"
                },
                {
                    "id": 17,
                    "name": "Kinderzimmer"
                },
                {
                    "id": 18,
                    "name": "Stufe 1"
                },
                {
                    "id": 19,
                    "name": "Badezimmer"
                },
                {
                    "id": 20,
                    "name": "Schlafzimmer"
                },
                {
                    "id": 21,
                    "name": "Wohnzimmer"
                },
                {
                    "id": 22,
                    "name": "Stufe 2"
                },
                {
                    "id": 23,
                    "name": "Esszimmer"
                },
                {
                    "id": 25,
                    "name": "Flur"
                }
            ],
            "token": "xxxxxxx",
            "waterBox": false
        },

**Comment by Dane03** [comment]
Solved, is "roomTimeout" new or did you change its default setting? 

I appreciate that we now have the option to add several rooms and the when set start the clean, however single room cleaning didn't work at mine now, not being aware that two switches instead of 1 had to be set if "roomTimeout" wasn't set.

I now entered "1" to have it running again.

**Comment by DocUltra** [comment]
ok that means I have to set the propertie roomTimeout to?? And another question, how do I get the information which ID is related to which room?

**Comment by Dane03** [comment]
See documentation, Used "1" as value, starts almost immediately.

Rooms: try and error.

Just set a rooms in HB with all IDs, start them in HomeKit and see the Xiaomi app where it heads to.

Then enter the correct name at the ID, or if not responding, delete the entry.

**Comment by afharo** [comment]
Hey @Dane03, I see you figured out the new `roomTimeout` property. I tried to warn about it in the Changelog as I understand this is a breaking change to all the room users.

I'll go ahead and close this issue. Feel free to reopen it if you feel like something is missing.
