### ISSUE TITLE
Room cleaning doesn’t work anymore

### ISSUE THREAD

**Issue by KayGundhardt** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#339]
Room cleaning doesn’t work anymore since the yesterday’s Homebridgeupdate V1.2.4: pushing the HomeKit button shows it’s enabled but the device doesn’t react at all. Only starting the vacuum cleaner within HomeKit still works.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
the same here ...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Ok, is already solved here : https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/337

**Comment by afharo** [comment]
Yeah, it was detailed in the Changelogs as a breaking change. You can find docs about the new behaviour in the README (Rooms section) :)

Closing this issue for now.
