### ISSUE TITLE
Problems with room selection - I just can not get this to work

### ISSUE THREAD

**Issue by billbazza** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#343]
Sorry if this feels like a repost but I've tried, what feels like, all the tips from past posts.

I have an S6 with auto room enabled and I get a list of random names with ID's in the logs. I then disable auto room and enter the ID's from the logs with 'friendly names'. My configuration ends up looking like the below but activating the switches in the app does not start the robot. Nothing happens. When I activate a switch, the following log is generated:

11/12/2020, 11:22:21 [Robochubby] ACT setCleaningRoom | roborock.vacuum.s6 | Enable cleaning Room ID 20.

   "accessories": [
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "Robochubby",
            "waterBox": false,
            "pause": true,
            "dock": false,
            "delay": false,
            "cleanword": "clean",
            "ip": "****",
            "token": "****",
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "silent": false,
            "roomTimeout": 0,
            "autoroom": false,
            "rooms": [
                {
                    "id": 16,
                    "name": "Kitchen"
                },
                {
                    "id": 17,
                    "name": "Utility Room"
                },
                {
                    "id": 18,
                    "name": "Office"
                },
                {
                    "id": 19,
                    "name": "Lounge"
                },
                {
                    "id": 20,
                    "name": "Hallway"
                },
                {
                    "id": 21,
                    "name": "Toilet"
                }
            ],
            "zones": []
        },

**Comment by adamabsurdum** [comment]
Hi, I have the very same issue. After updating to the most recent version in Homebridge, I can't get it to work. I even re-added the accessory, revised the map, etc. All other functions work, except room cleaning. What am I doing wrong?

**Comment by okonet** [comment]
Same. It stopped working after the latest update. It said it's a breaking change but I cannot find anything different in the config.

**Comment by tozwierz** [comment]
Same for me. Stoped working.

**Comment by ab1781** [comment]
Just some thoughts, maybe you already checked this: Room cleaning also did not work here right after updating. Turns out "roomTimeout" was not in the config. Added it manually and all is fine again, moreover I could now clean several rooms via one Siri call. 
Another thought: Maybe it could help to set "roomTimeout" higher than "0"? I have set it to "8" seconds, just to have enough time to tell Siri all the rooms I would like to be cleaned.

**Comment by okonet** [comment]
@ab1781 are you saying that `roomTimeout` is required in order to work?

**Comment by ab1781** [comment]
Absolutely. Just give it a try and add in in your config, like this

"roomTimeout": 8,

After the last update Siri commands just turns the room switches on and nothing further happens. It obviously needs the  "roomTimeout" which makes the robot run (automatically after your Siri command). Don't know why the last update didn't add that in the config.

**Comment by billbazza** [comment]
roomTimeout greater than 0 was the key! Thanks so much. 

To be honest, I didn't even see the room timeout in the settings!

**Comment by ab1781** [comment]
> roomTimeout greater than 0 was the key! Thanks so much.

You are welcome, great to hear it works now. 

> To be honest, I didn't even see the room timeout in the settings!

Me, too. Couldn't see it however as it wasn't in the config after update. Now after adding it manually it is also visible in the setting. 

Suggestion for next update: roomTimeout greater than 0 as default

**Comment by afharo** [comment]
> Suggestion for next update: roomTimeout greater than 0 as default

That's being tracked in this discuss issue: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/338

Closing this issue

**Comment by okonet** [comment]
Thanks. Adding the `roomTimeout` worked like a charm.
