### ISSUE TITLE
Room cleaning suddenly stopped working

### ISSUE THREAD

**Issue by frassesfik** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#347]
I'm using latest version, v0.16.1.

I've been using this plugin with my Roborock S6 for a long time, over the course of many plugin updates and never had any issues until now. For some reason, the room cleaning has suddenly stopped working. No changes in the plugin settings or in the Roborock settings in the Xiaomi Home app.

The settings in my config file are these (removed the token) : 

{
            "name": "Margit",
            "ip": "192.168.10.42",
            "token": "XXXXXXXXXXX",
            "waterBox": false,
            "pause": true,
            "pauseWord": "pausa",
            "findMe": true,
            "findMeWord": "var är du",
            "dock": true,
            "delay": false,
            "cleanword": "Städa",
            "autoroom": false,
            "rooms": [
                {
                    "id": 16,
                    "name": "Vardagsrummet"
                },
                {
                    "id": 17,
                    "name": "Samuels rum"
                },
                {
                    "id": 18,
                    "name": "Köket"
                },
                {
                    "id": 19,
                    "name": "Hallen"
                },
                {
                    "id": 21,
                    "name": "Sovrummet"
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }

I have no clue what has happened. I tried removing the rooms config and enable autoroom just to double check the room IDs but they were the same. Other functions as "find me" and complete cleaning is working from within HomeKit and the room cleaning is working from the Xiaomi Home app but no longer within HomeKit.

Any ideas?

**Comment by afharo** [comment]
Hey! If you take a look at the [Changelogs](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases), you'll notice there were some breaking changes on 0.15.0 to the Rooms function: They won't automatically start cleaning to allow users to trigger multiple rooms to clean at the same time. On 0.16.0 we added the option `roomTimeout` to bring back the similar previous behaviour. That new option is detailed in the README under the ["Room cleaning" chapter](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#room-cleaning)

**Comment by afharo** [comment]
I think the question was answered. I'll close this issue. Feel free to reopen if there are any follow-up questions.
