### ISSUE TITLE
Delay (beta) does not work

### ISSUE THREAD

**Issue by Christian-CFP** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#356]
Hi there,
the delay function does not work for me.
Hombridge Service does not start after setting delay to true.

It would be nice to have a delay, because for roomcleaning. If set multiple rooms the cleaning mode should have a delay for 3 seconds to wait until every room switch is set to on.

**Comment by afharo** [comment]
Hi @Christian-CFP, I think the option you're after is `roomTimeout` (explained in the [readme](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#how-it-works))

The option `delay` is for something else: It tries to wait for the connection to be established on startup before registering the plugin in Homebridge, although it doesn't work in all OSs.

**Comment by Christian-CFP** [comment]
Sounds great but I tried it and set it to 10 sec. and no. Did not get all rooms. It started. Did not wait 10 sec.

**Comment by Christian-CFP** [comment]
1 or 2 sec will work but I wanted to know if the robo will wait the time.

**Comment by afharo** [comment]
Hmm! I'll need to test it myself to debug the reason. AFAIK, it should wait the specified time.
