### ISSUE TITLE
Plugin not allowing Homebridge(1.3) to boot

### ISSUE THREAD

**Issue by Mikellas** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#361]
Hi ,

I have just updated Homebridge and services wont come up due to this plugin.
Once I choose to deploy it as a child bridge ,homebridge starts up just fine but the plugin wont give me a barcode to scan in Homekit

Can someone assist?

Thanks

**Comment by Mikellas** [comment]
Ok figured out exactly whats causing this I believe
Its the startdelay which is a beta feature for the roborock

**Comment by mitch7391** [comment]
I have found the start delay completely kills my homebridge `v1.3.0` but even without that this plug-in has my homebridge running but caught in an endless loop before it can add my accessories to the accessories tab to config-ui-x and therefore Homekit is left as no response.

**Comment by mitch7391** [comment]
@afharo is this something that might be able to have some urgency placed on it? As I cannot use homebridge `v1.3.0` with this plug-in installed by the looks.

**Comment by Mikellas** [comment]
What has worked for me for now is leave the settings page as below and restart HB
Let me know if it works
![Capture2](https://user-images.githubusercontent.com/62306024/108674908-af7a5300-74ee-11eb-987d-c19e223bf25b.PNG)

**Comment by mitch7391** [comment]
That did not work for me sadly...

**Comment by afharo** [comment]
Heya! It looks like we have to remove the `delay` option. To be fair, I never was a fan of it, because it had different behaviours depending on the OS. I'll create a PR to solve it and will test 1.3.0 on my end.

**Comment by afharo** [comment]
It starts OK for me in `1.16.2` (as long as I don't use the `delay` option). Can you confirm, please?

**Comment by mprspliid** [comment]
works also for me, when I do not enable delay options

**Comment by mitch7391** [comment]
@afharo this has fixed it for me! Thank you so much for the quick fix, I can now use homebridge `v1.3.0`! :)

**Comment by afharo** [comment]
Thank you all for confirming! I'll go ahead and close the issue :)
