### ISSUE TITLE
Warning from characteristic

### ISSUE THREAD

**Issue by Fr34k9** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#366]
Following error/warning appear once like every 10minutes. Sometimes the error is only shown once, sometimes like 6 times after each other.

[2/23/2021, 12:45:19 PM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic was supplied illegal value: number -47.437962962962956 exceeded minimum of 0. See https://git.io/JtMGR for more info.

Cheers & thx!

**Comment by afharo** [comment]
Hmm, interesting! That's weird! I'll take a look!

**Comment by afharo** [comment]
It should be fixed in `homebridge-xiaomi-roborock-vacuum@0.17.1`

**Comment by Essdy** [comment]
> It should be fixed in `homebridge-xiaomi-roborock-vacuum@0.17.1`

It is still ongoing issue unfortunately. :(

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/discussions/449
+
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/386

**Comment by afharo** [comment]
Hopefully https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.25.1 should fix this.
