### ISSUE TITLE
Roborock App - Token - S6 maxv

### ISSUE THREAD

**Issue by marcel293** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#368]
Hi @all,

because of the camera remote I want to use the **Roborock-App**, but I can not find the necessary token (like with the Xiaomi Home App). With my old S5 max everything works fine, but with S6 max I need the Roborock App.

Form my iOS BackUp I export the **com.roborock.smart.plist**. I find e.g. the room IDs, but no working token. There is a property called token, but it's 73 signs long.

Any Ideas how I can use Roborock App and Homebridge. Thx a lot!
Marcel

**Comment by marcel293** [comment]
My actual solution: In the Roborock-App you have the possibility to add Siri Shortcuts e.g. for Rooms, Start, Pause, Dock, Vacuum levels,... In this case no homebridge is needed.

**Comment by afharo** [comment]
hi @marcel293 there's another issue where folks are trying to find out the way to obtain the token from the Roborock app: #104
