### ISSUE TITLE
HB stopped after update while loading second room for S6

### ISSUE THREAD

**Issue by panthertom** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#369]
Hello,
my HB docker does not boot / is stopped after the update tov1.3.1.
I just restored my config - but no luck.
the process stopped while loading the second room for the S6.
![HB v1 3 1 Xaomi S6](https://user-images.githubusercontent.com/68554664/109541517-2d78c400-7ac4-11eb-8a50-58d726842428.jpg)
please feel free to ask any question.
Thanks for your support
Kind regards
Thomas

**Comment by panthertom** [comment]
running on DMS Synology ...

**Comment by afharo** [comment]
Hi @panthertom!

In order to _try_ to help you, I need to ask some questions:

- Are you running the latest version of this plugin?
- How does your config look like (feel free to obscure any data that you might not want to share like the token, IP, etc.)?

**Comment by panthertom** [comment]
Hello Alejandro,

Thanks for your reply and your support.

1. Yes I’m running the latest version. I updated all plugIns before the HB update

2. I deleted all rooms in the plugin to make the HB work again 

3.  My config






Please let me know if I can try anything or in case you need more information.

Thanks again for your support.

Kind Regards
Thomas

**Comment by panthertom** [comment]
Hi Alejandro,
pleases let me know, if you haven't received the screenshots.
Thanks and kind regards
Thomas

**Comment by afharo** [comment]
@panthertom yeah... I think the screenshots didn't make it to the comment :(

**Comment by afharo** [comment]
@panthertom we've released a couple of upgrades in this area, so hopefully this issue is resolved. I'll go ahead and close this issue. Feel free to reopen it if you think it's not solved on your end yet.
