### ISSUE TITLE
No Response Roborock S5 Max

### ISSUE THREAD

**Issue by EdvardasKey** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#371]
Hi, maybe can anyone help me to add Roborock S5 Max to Home Kit? Installed Homebridge Xiaomi Roborock Vacuum, added the same name and IP address and still no response. What and where i have to add to make it available? :)

**Comment by afharo** [comment]
Did you get the token as explained in the README?

**Comment by EdvardasKey** [comment]
yes, token is abcdef1234567890abcdef1234567890

**Comment by afharo** [comment]
That looks like a made-up token to me. You need to extract the token that is generated by your vacuum when registering in the Xiaomi Home app.

**Comment by EdvardasKey** [comment]
well.. installed xiaomi home app, but can't find anything about "token". Could you please tell me, where is it? Have scrolled all app menu twice.. nothing..

**Comment by afharo** [comment]
There are a few methods about extracting the token in the README: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#xiaomi-token

**Comment by EdvardasKey** [comment]
im runing Mac Os, so this is the end for me. Thanks anyway

**Comment by afharo** [comment]
So do I, and I extracted mine long ago using this method: https://python-miio.readthedocs.io/en/latest/discovery.html#tokens-from-backups

**Comment by EdvardasKey** [comment]
So i extracted sqlite file from my iphone backup. Please, can you help me - how to extract token from it? "the miio-extract-tokens can be used to extract the tokens from it."  <- do i have to write this command to terminal?

**Comment by EdvardasKey** [comment]
made it, thanks!!!

**Comment by afharo** [comment]
@EdvardasKey it looks like you made it work. I'll go ahead and close this issue. Feel free to reopen it if you need any follow-up.
