### ISSUE TITLE
 "powerMode": {                     "show": "HEX..."

### ISSUE THREAD

**Issue by wroblewski6** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#372]
WHat button should I learn for this >>??<< 
What that will do ??

I read wiki and no information about it 

"powerMode": {
                    "show": "HEX..."

**Comment by afharo** [comment]
Hi @wroblewski6, can you provide more context? I'm not entirely sure what your question is about, and what you're trying to achieve.

Are you trying to extend this plugin to support a new model? Where did you get those fields?

**Comment by timesl** [comment]
The powerMode is found in this sample json
https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/config-sample.json-W1

but not found from this wiki
https://broadlink.kiwicam.nz/#tv

**Comment by afharo** [comment]
@timesl those links point to a different `homebridge` plugin. What does Broadlink RM have to do with this plugin?

**Comment by afharo** [comment]
I'll close this issue because it seems not relevant to this plugin. Feel free to reopen it with more context on how it relates.
