### ISSUE TITLE
Roborock S7 support

### ISSUE THREAD

**Issue by cgilis** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#384]
Hi, 

Will this plugin support Roborock S7?

Thx!

![gsmarena_002](https://user-images.githubusercontent.com/62599539/111989732-71367a80-8b12-11eb-80e4-23434eaa3456.jpg)

**Comment by discostur** [comment]
Would also be interested in S7 support ...

**Comment by afharo** [comment]
The Roborock S-line is fairly standard (Xiaomi usually doesn't apply any breaking changes in those models). However, it's best to test it and find out any tweaks we might need to apply (usually defining the watermodes and any other speeds it may have).

If you own one, would you mind giving it a try?

**Comment by cgilis** [comment]
> The Roborock S-line is fairly standard (Xiaomi usually doesn't apply any breaking changes in those models). However, it's best to test it and find out any tweaks we might need to apply (usually defining the watermodes and any other speeds it may have).
> 
> If you own one, would you mind giving it a try?

Yes, of course! Mine is coming in the next days.. I'll repot back to you.

One small question, I saw there was no Mi Home support for this model, is this going to be a big dealbraker?

Kr,

**Comment by afharo** [comment]
> One small question, I saw there was no Mi Home support for this model, is this going to be a big dealbraker? (I use the Mi Home app to get the token)

We need to find a way to support Roborock's App tokens. We're discussing about it in #104

**Comment by Didlove** [comment]
It works with the Mi Home App. And the S7 is working with the plugin.
But it seams that the autoroom function is not working. I named the rooms but none is appearing in homebridge.

**Comment by cgilis** [comment]
> It works with the Mi Home App. And the S7 is working with the plugin.
> But it seams that the autoroom function is not working. I named the rooms but none is appearing in homebridge.
> 
> Edit: sorry missed the instruction for adding the rooms.

Thx!!

How did you add it to MI home?

**Comment by Didlove** [comment]
![4AB482D1-3BD1-44A9-BDA5-D90AF39ACE43](https://user-images.githubusercontent.com/77897665/112527723-a279a980-8da3-11eb-8618-bcdcefb14a9c.jpeg)
 
 I am on iOS. Just hit the + Button.

**Comment by cgilis** [comment]
Ok, I've checked on the EU servers, and the S7 is available over there (and some other devices too)

Have a fine day!

**Comment by u20p17** [comment]
> > One small question, I saw there was no Mi Home support for this model, is this going to be a big dealbraker? (I use the Mi Home app to get the token)
> 
> We need to find a way to support Roborock's App tokens. We're discussing about it in #104

Hi,
I just opened an issue #387 where a link is included for extracting the Tuya token. but for using it you would have to implement another protocol. Would be nice if this would be possible (Y) 

Thanks!

**Comment by cgilis** [comment]
Ok the extraction of the token works with the Mi Home app.

But I've this error in homebridge:
[Roborock S7] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

**Comment by cgilis** [comment]
Roborock S7 works with Mi Home (europe region) so extraction of the token is easy.

**Comment by cgilis** [comment]
> It works with the Mi Home App. And the S7 is working with the plugin.
> But it seams that the autoroom function is not working. I named the rooms but none is appearing in homebridge.
> 
> Edit: sorry missed the instruction for adding the rooms.

Hi, did you do this with the "Automatic Room Detection" button in the settings?
Seems not to work with me.

Thx
