### ISSUE TITLE
Roborock S7 - Customize function

### ISSUE THREAD

**Issue by cgilis** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#391]
Hi,

Small question, when the roborock S7 has started cleaning within the homekit app the 'Customize' rules are not being used.
So it's mopping the whole area instead of skipping some parts. Is this an issue with the plugin, or..

Kr,

![IMG_9712DBF70F2C-1](https://user-images.githubusercontent.com/62599539/113874091-b6ff6e00-97b5-11eb-8a70-5292fa97b417.jpeg)

**Comment by afharo** [comment]
Oh! My model doesn't support that option. AFAIK, the `custom` mode is usually represented by this plugin as 100% speed in Homekit. However, I'm not entirely sure how it behaves when cleaning multiple rooms and the custom mode is ON. I'm not sure how to tell the robot how to use each room's specific custom mode.

**Comment by cgilis** [comment]
Maybe this will be fixed in a firmware update of the roborock.

But it is strange :-)

**Comment by Maintraxx** [comment]
@cgilis How did you extract your token from the S7?

**Comment by cgilis** [comment]
> @cgilis How did you extract your token from the S7?

With the Mi Home app, but your region has to be Europe to work..

**Comment by afharo** [comment]
I think https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/439#issuecomment-1073837452 has some pointers about how the custom mode works.
