### ISSUE TITLE
Access Roborock in Guest Wifi

### ISSUE THREAD

**Issue by fakio87** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#392]
Hi, 

I used to leave my Roborock S5 in the Guest Wifi. This worked well as I could access through App via Internet despite local wifi and keep Xiaomi out of my actual wifi.

Is there any way to use the plugin via http despite local IP?

This way I use my Robonect as it supports a web service address as well.

Thank you in advance!
Fakio

**Comment by afharo** [comment]
Hi @fakio87,

AFAIK, as long as `homebridge` has access to that local IP, I don't see why it wouldn't work.

**Comment by afharo** [comment]
It looks like the question was answered... I'll close this issue. Feel free to reopen if there are any follow up questions.
