### ISSUE TITLE
How to set up Watermode and Fan Speed levels

### ISSUE THREAD

**Issue by FranciRoosters** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#399]
I'm very new to Homebridge and I don't really understand much of it. Where and how exactly do I have to set the fan speed and water level modes? I already have the basic configuration. Model is S5 Max.

"name": "Jarvis",
            "ip": "xxx-xxx-xx-xx",
            "token": "token",
            "waterBox": true,
            "silent": false,
            "pause": false,
            "pauseWord": "Pause",
            "findMe": false,
            "findMeWord": "Where is Jarvis?",
            "dock": true,
            "cleanword": "Start Jarvis",
            "roomTimeout": 0,
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"

**Comment by afharo** [comment]
Hi @FranciRoosters,

The way this plugin works right now is by fixed-per-model jumps.

In [here](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/models/models.js#L34-L39) you can see the S5 Max model uses the [watermodes.gen1](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/models/watermodes.js#L5-L30) and the [speedmodes gen4+custom](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/models/speedmodes.js#L182-L219).

I hope these links help you understand how the fan speeds translate to the modes :)

**Comment by FranciRoosters** [comment]
Thank you for these, but I still don’t understand which information I need and where exactly I have to paste it in my config file on Homebridge. Thank you.

Config file right now:

{
            "name": "Jarvis",
            "ip": “IP",
            "token": “TOKEN",
            "waterBox": true,
            "silent": false,
            "pause": false,
            "pauseWord": "Pause",
            "findMe": false,
            "findMeWord": "Where is Jarvis?",
            "dock": true,
            "cleanword": "Start Jarvis",
            "roomTimeout": 0,
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"
        }
    ],

**Comment by afharo** [comment]
You don't need to add anything to the configuration. This plugin is supposed to automatically identify your robot's model and will adjust the sliders to work as per the levels I shared above.

**Comment by FranciRoosters** [comment]
I see. I have one last question: so far I’ve used my robot just for regular vacuuming, but when I want it to mop, how can I tell the Home app I want the robot to just mop? I’m asking because currently it seems that if you turn on the fan for regular vacuuming, the Water Box comes on too and it always shows 70% even when there’s no water. 

Thank you.

**Comment by afharo** [comment]
I think https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/439#issuecomment-1073837452 answered this question 😇
