### ISSUE TITLE
HomeKit automations won't start the robot

### ISSUE THREAD

**Issue by martindinicolino** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#406]
I can start the robot manually in the Home app, ask Siri to turn it on or use Shortcuts, all of these work reliably both when I am at home or remotely, but home automations are always unable to start the robot. For example the robot won't start for the "time of day" or "people leave" automations.

There is no error codes in the homebridge logs, nor was I able to spot any commands there when the time of day occurred.

Any idea on how to fix it?

**Comment by afharo** [comment]
Hi @martindinicolino,
I recall having similar issues like a year ago. The plug-in worked just fine, but for some reason, the automations randomly worked.

After a lot of investigation, it just happened that I had an iPad as my Home hub, and it was pausing the HomeKit service for memory/battery reasons 🤷. The problem went away the moment I bought an Apple TV. I guess it would also be solved with a HomePod Mini (also cheaper).

Is your Home hub also an iPad?

**Comment by martindinicolino** [comment]
Hi @afharo,

thank you very much for your reply.

As a matter of fact I am using an iPad as my home hub (but it is constantly plugged in and all other automations work normally, the only ones that don‘t work are the ones associated with this plugin).

Sadly Homepods are not sold in the country i currently live in, but if i can get my hands on one i‘ll let you know what happens.

**Comment by martindinicolino** [comment]
The robot actually started yesterday (so far the only time it worked), but today it didn't and I found the following logs:

[5/16/2021, 4:19:22 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[5/16/2021, 7:01:53 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Firmware Revision' was slow to respond! See https://git.io/JtMGR for more info.
[5/16/2021, 9:45:03 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.

not sure if this is related or not;

anyhow https://git.io/JtMGR suggests to report the issue to the developer

**Comment by afharo** [comment]
Hi @martindinicolino,

It looks like the robot is taking too long to reply (maybe due to some network issues?). I've created https://github.com/homebridge/homebridge/issues/2931 to find out what's the timeout Homebridge enforces for showing that slow-log.

**Comment by martindinicolino** [comment]
Following your recommendation I decided to have a HomePod mini shipped to me from a friend abroad, it arrived on Friday.
I was thinking to wait a week and see how it affects the automations before coming back to you (the good news is that so far it hasn't missed any time of day automations, so thank you very much for that suggestion! away from home automations still aren't working, but apparently a lot of iOS 14 users seem to have that issue, so I suppose that's causing it for me as well).

I do however still see the error messages in the logs:
[5/24/2021, 3:22:30 AM] [Xiaowa E Series] ERR getState | {"code":"timeout"}
[5/24/2021, 3:23:00 AM] [Xiaowa E Series] ERR getState | {"code":"timeout"}
[5/24/2021, 3:23:30 AM] [Xiaowa E Series] ERR getState | {"code":"timeout"}

I'm not too sure on the network issues tbh, the router, Homebridge and robot are all in the same room and I haven't noticed any.

Thank you so much for looking into this and let me know if I can do anything to help from my end.

**Comment by afharo** [comment]
I'm glad that it worked for you!

> [5/24/2021, 3:22:30 AM] [Xiaowa E Series] ERR getState | {"code":"timeout"}

Oh! I notice that model does not support the `getState` request. That's the reason for the `{"code": "timeout"}`. I have a task somewhere to stop requesting that for that model to avoid that annoying noise. Please, let me know if there's anything else in the future.
