### ISSUE TITLE
Room cleaning starting error

### ISSUE THREAD

**Issue by TheBassfly** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#421]
Hey there

In the recent version the room cleaning in Homekit has a small bug, I think.
When you start the cleaning via the room switch, nothing happens. You have also to set a fan speed for the Robot.

As far as I remember in the older versions this happened automatically. Or is this a new feature?

Thank you.

**Comment by Bene2103** [comment]
I've discoverd this myself right now.

You have to set the room timeout above 0, i've set it to 1 and it works flawless.

**Comment by TheBassfly** [comment]
> I've discoverd this myself right now.
> 
> You have to set the room timeout above 0, i've set it to 1 and it works flawless.

Interessting
Where do I set this timeout?

**Comment by afharo** [comment]
Yeah! This was added to allow selecting multiple rooms before the cleaning starts on its own. Sorry for the confusion.
