### ISSUE TITLE
No response Icon shows up in the home app for roborock s7

### ISSUE THREAD

**Issue by geozakk** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#422]
I recently added my roborock s7 but for some reason I see a no response indication in the home app. But all the vacuum functions work well. 

Although I noticed the below warning flooding the logs. 

WARNING WAR changedSpeed | roborock.vacuum.a15 | Speed was changed to 106%, this speed is not supported

**Comment by agafirss** [comment]
same problem

**Comment by Skjall** [comment]
This package seems to be dead.

you can fix this by adding a section for the S7 to the models/models.js:

After this:
```
  "roborock.vacuum.a11": [
    {
      speed: speedmodes["gen4+custom"],
      waterspeed: watermodes["gen1+custom"],
    },
```

add this:

```
  // S7
  "roborock.vacuum.a15": [
    {
      speed: speedmodes["gen4+custom"],
      waterspeed: watermodes["gen1+custom"],
    },
  ],
```
