### ISSUE TITLE
problem with siri trigger while running in child bridge mode

### ISSUE THREAD

**Issue by elfive** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#428]
environment:
```
system: Ubuntu Bionic Beaver (18.04.5 LTS)
node js: v14.17.5
npm: v7.20.6
user: root
docker: yes
service mode: yes
```

because of some other plugin slows down the main bridge, I changed xiaomi-roborock-vacuum config, runs this plugin in child bridge mode, everything seems ok after I set it up in homekit app.
But when I say "hey siri, clean up guest room" to homepod, it response me with "clean guest room not responding".
After I restore config.json, and this plugin not running in child bridge mode, it works fine.
There is no additional output log in child bridge mode.

**Comment by afharo** [comment]
Hmm, for child bridge modes, I must redirect you to the `homebridge` team. Not sure how they implemented them, and what might be happening under the hood. Sorry.

**Comment by elfive** [comment]
> Hmm, for child bridge modes, I must redirect you to the `homebridge` team. Not sure how they implemented them, and what might be happening under the hood. Sorry.

yeah, I agree with you, I just let the developer knows first.
thank you for your reply.^_^
