### ISSUE TITLE
What is the Occupancy sensor that I see in the HomeKit?

### ISSUE THREAD

**Issue by miguelpruivo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#430]
Looks like it can detect if a person is in the room? How so? Also, how can I select different rooms? (Roborock S50)

**Comment by afharo** [comment]
Hi! The occupancy sensor refers to the dock. So, when the robot is docked, it will be ON. When it leaves the dock, it's supposed to be OFF.

**Comment by miguelpruivo** [comment]
Thank you for clarifying.

**Comment by afharo** [comment]
Happy to help! I'll go ahead and close this issue. Feel free to reopen it if you need anything else.
