### ISSUE TITLE
Roborock S7 how to turn on the vacuum cleaner mode without washing the floor?

### ISSUE THREAD

**Issue by svsiznoi** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#439]
Hello everyone. There is a roborock s7 vacuum cleaner, I can't turn off the waterBox in the home kit to sometimes run my vacuum cleaner without wet cleaning. When I set the waterBox slider to 0, the robot automatically turns off and leaves for the dock. Just like simply turning off the waterBox button sends the robot to the docking station. Can you tell me the solution?

**Comment by afharo** [comment]
Hmmm! That's a good one! I may need to take a look at the code. My model doesn't have a separate water slider... so I can't test it myself.

My gut feeling though, thinks that you should select a different fan speed (probably the speed you're selecting is the mop mode)

**Comment by francescosabia** [comment]
hi! i have the same problem.. when turning off waterbox it comes mack to the dock... is better to have the switches for the modes and not the fan (like the xiaomi cooling fan plugin) so we can adjust it better...

**Comment by TheRealSimonMlr** [comment]
Just an Idea: What might be even easier is when mapping 1% to off [in this file](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/models/watermodes.js), so you could just create a shortcut or scene which uses 1% watering fan speed, which in fact would turn it off.

**Comment by TheRealSimonMlr** [comment]
Just to confirm, it is working when editing the [watermode.js like this (Line 8 & 35)](https://gist.github.com/TheRealSimonMlr/5081dd36ec99a6ef16d0be4724beff79) and setting the Fan-Speed to 1% (In my case, via shortcut).
The only downside is that the watering-fan displays in HomeKit as "running", even if it really means there is no watering (At least if set to 1%).

If you like this solution @afharo, I would be happy to create a pull-request ;)

**Comment by afharo** [comment]
It looks like @TheRealSimon42 found the solution. I'll go ahead and close this issue. Feel free to reopen if there's anything else pending to be done.
