### ISSUE TITLE
Roborock Annoying noise 

### ISSUE THREAD

**Issue by migudev96** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#445]
When i Start the Roborock it is all all fine and works very well. But when the Roborock get started by an automation, there is every secound the „ding“ noise non stop, like you would change the vaccum options of the suction power or the wipe intensity. I only can stop the noise when i turn the vaccum off and on again or when i restart the homebridge.

Hope anyone can help me. I use the newest version of the Plugin, and the newest Update of the Roborock and HOOBS Homebridge version. My Roborock is the Roborock S7.

**Comment by afharo** [comment]
Wow @migudev96! That is an interesting issue! I can tell you for certain that the plugin does not intentionally emit/enable any "ding" sounds.

Is it still occurring? Any logs you can share from HOOBS?

**Comment by afharo** [comment]
This issue seems stale... I'll go ahead and close it. Feel free to reopen if you have any feedback.
