### ISSUE TITLE
ERR getState | {"code":"timeout"}

### ISSUE THREAD

**Issue by fmpmsilva** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#459]
Hi there. 

Just tried to connect my new Mi Vaccum Mop and I get ERR getState | {"code":"timeout"}.

Any ideas?

Thanks

**Comment by fmpmsilva** [comment]
Got the token in tokenextractor.exe

**Comment by afharo** [comment]
This issue seems stale. I'll go ahead and close it. Feel free to reopen it if there's any feedback.
