### ISSUE TITLE
Token might be wrong

### ISSUE THREAD

**Issue by BaRaD5** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#463]
Hey!
I’m having issue while connecting my roborock s7
Says token might to wrong
I did reset the WiFi and got a new token but still says the same
Could any one point me to solve this?

**Comment by BaRaD5** [comment]
Doing the inspect command will show all the info about the vacuum but in HomeKit shows no response

**Comment by afharo** [comment]
Can you share the logs that you get, please?

**Comment by BaRaD5** [comment]
Had to completely remove the plugin and install it again, changing versions didnt help.
Now everything works fine, thank you!
