### ISSUE TITLE
Room Cleaning

### ISSUE THREAD

**Issue by ivofernandespt** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#468]
I have one S7.
I mapped rooms on HB as described but even I defined timeout to 0, in home app I need to turn on main fan switch after turning on room switch. 
But the biggest problem is that robot starts cleaning but after a few seconds it says that cleaning is completed I it will return to dock.

Can you please help?

**Comment by LukasEm** [comment]
Hello,
I have the same issue, model S7 as well.

**Comment by afharo** [comment]
Hi! The last time I saw that happening is because the room IDs didn't match (probably the map was updated)

**Comment by ivofernandespt** [comment]
Can you please help how to map IDs? Following instructions it doesn’t work.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Alejandro Fernández Haro ***@***.***>
Enviado: Monday, December 27, 2021 9:44:34 PM
Para: homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum ***@***.***>
Cc: ivofernandespt ***@***.***>; Author ***@***.***>
Assunto: Re: [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum] Room Cleaning (Issue #468)


Hi! The last time I saw that happening is because the room IDs didn't match (probably the map was updated)

**Comment by stonemaan** [comment]
> Hi! The last time I saw that happening is because the room IDs didn't match (probably the map was updated)

I have the same issue with S6 on Valetudo (room names and IDs updated and match between Homebridge and robot) and S5max via Xiaomi Cloud. Robot starts room cleaning and cancels after a few second and moves back to the dock.

**Comment by Dimitris947** [comment]
Any solutions? I have the same problem

**Comment by afharo** [comment]
How does your config look like. I believe that behavior is caused by wrong IDs: the robot tries to trace a route to the room to clean, but it finds out it cannot successfully identify the room. Hence, it cancels and goes back to the dock.

**Comment by afharo** [comment]
It looks like this issue is stale... I'll go ahead and close it. Feel free to reopen if there's any relevant feedback.
