### ISSUE TITLE
Warning messages from plugin

### ISSUE THREAD

**Issue by petrocino** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#475]
Get several warning messages on my Homebridge log:

[1/24/2022, 2:59:54 PM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by petrocino** [comment]
Hi there.

There's any updates about it? Still receiving these warnings

`[3/22/2022, 5:00:52 PM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.`

**Comment by petrocino** [comment]
Hi there.
No one have ever commented it.
Any ideas??

**Comment by afharo** [comment]
Hi @petrocino. Apologies for the late reply. Can you share what information is shown in the preceding logs that look like:
```
INF getCareSensors | ...
INF getCareFilter | ...
INF getCareSideBrush | ...
```

I wonder what it looks like for the values that you get, so we end up with a `NaN` number 🤔

**Comment by afharo** [comment]
I think recent updates worked a bit more on ensuring the numbers are not `NaN`. I'll go ahead and close this issue. Feel free to reopen if it's still happening.
