### ISSUE TITLE
Additional icons for hoobs.. currently it shows as a fan, can we add couple of icons.. one for robot vacuum and other for doc?

### ISSUE THREAD

**Issue by Taureans** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#493]

**Comment by afharo** [comment]
Hi @Taureans the icons are provided by Apple's HomeKit. Unfortunately, they don't support vaccums or docks as of now so this plugin hacks around that limitation by exposing the robot as a fan.

Once Apple supports them, I'll make sure to convert the service used.

I'll go ahead an close the issue for now.
