### ISSUE TITLE
Add support for Roborock S7 maxV

### ISSUE THREAD

**Issue by nicolasbigot** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#495]
Just tried installing the plugin with Roborock s7 maxV, but getting this error in the logs :
`[Roborock S7 maxV] WAR changedSpeed | roborock.vacuum.a27 | Speed was changed to 106%, this speed is not supported`

**Comment by afharo** [comment]
Thanks to @khad, https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.22.0 will now support this model.
