### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by atol71** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#509]
I am getting:
(node:10711) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
That disappears after restart of plugin bridge. Connected Roborock E5 Roborock S7.

**Comment by afharo** [comment]
Thanks for reporting! I'll look into the implementation to figure out what listeners are set and how can we control it.

**Comment by afharo** [comment]
@atol71, a lot has changed in this plugin since this issue was opened. Is this still an issue?

**Comment by atol71** [comment]
Have not had any notifications of late. On my behalf case is closed.

**Comment by atol71** [comment]
Closed
