### ISSUE TITLE
Plugin breaks with 0.24.0

### ISSUE THREAD

**Issue by nicolasbigot** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#518]
Plugin seems to break since latest release with following error in logs:
`[homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Model': Unhandled error thrown inside read handler for characteristic: callbackifyLib is not a function. See https://homebridge.io/w/JtMGR for more info.`

**Comment by afharo** [comment]
Oops! Thanks for the heads up! Looking at it right now! I'll unpublish the version to avoid other folks from upgrading

**Comment by afharo** [comment]
Fixed in version https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.24.1
