### ISSUE TITLE
v0.26.0 SET handler returned write response value error

### ISSUE THREAD

**Issue by Christian-CFP** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#529]
Hey, got a similar plugin fail message after updating to 0.26.0. But after restarting the plug-in it was fine. 

But if I start something via HK a write error occurres. 

[HOME Bridge Pause@On] SET handler returned write response value, though the characteristic doesn't support write response

It will start but I get this error message everytime I start cleaning, Pause etc.

**Comment by afharo** [comment]
I think I know why... thank you for letting me know... May I ask: is it an error or a warning?

**Comment by Christian-CFP** [comment]
Ok tried 0.26.1

This error appears:

[31mThe plugin "homebridge-xiaomi-roborock-vacuum" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin![39m

**Comment by afharo** [comment]
Gotcha! Re the `'hap-nodejs'` warning, I created #533 to track that.

Let's keep this issue for the SET handler one.

**Comment by afharo** [comment]
The SET handler warning should be resolved in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.26.2

**Comment by Christian-CFP** [comment]
Both fixed in 0.26.3 ! THX!

**Comment by afharo** [comment]
@Christian-CFP Thank you for confiming! 🧡
