### ISSUE TITLE
Error: Cannot find module 'hap-nodejs'

### ISSUE THREAD

**Issue by HuettmannH** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#530]
my Homebridge run as a docker.
After I update to version 0.26.0 I read this error. When I store version 0.23.0 no error 
I have model Roborock S7 pro

**Comment by luc-ass** [comment]
This is a duplicate to #528

**Comment by afharo** [comment]
Thank you for the head up! I'll submit a fix in a bit. I'll update here.

**Comment by afharo** [comment]
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.26.1 should have fixed it :)
