### ISSUE TITLE
Goto target problem

### ISSUE THREAD

**Issue by maisun** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#539]
Hi,
Noticed a problem with Goto target function: when I turn off the switch it triggers another goto command, instead of going back to dock. Is it supposed to be like that? I have tried a few times the device goto target with an error (due to obstacles) but there is no way that I can ask it to go back to dock station. In my opinion the logic should be when switching off goto, it should send docking command.

**Comment by afharo** [comment]
cc'ing @luc-ass for awareness as he introduced the feature.

**Comment by luc-ass** [comment]
You are right. I'll try to find a solution.

**Comment by luc-ass** [comment]
Well, I found a fairly well written doc of the API [here](). From my understanding, the button should act like this:
* Turn goToButton on → go to specified location (essentially the way it works right now)
* Turn goToButton off → go back to dock ([reference](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/basic.md#command-4))
* Button automatically turns off as soon as status is not `13: going-to-location` or `3: waiting` ([source](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/13f844a10403808c9606377a5b0250e64f0db584/src/miio/lib/devices/vacuum.js#L54))

Additional thoughts?

**Comment by luc-ass** [comment]
@afharo Still wrapping my head around TS. Can you point me to the correct file, where for example `goToLocation(){}` is defined? It used to be in [/src/miio/lib/devices/vacuum.js](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/c75212968507d385215deb0590eed39124095c89/src/miio/lib/devices/vacuum.js). Is that still true?

**Comment by luc-ass** [comment]
[This](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/compare/master...luc-ass:homebridge-xiaomi-roborock-vacuum:master) would be my suggestion for now...

**Comment by luc-ass** [comment]
@afharo can you tell me how to test TS locally? I was able to clone the repo into a folder, as I do normally, but `npm install` or `npm install typescript` doesn't result in a working plugin.

**Comment by luc-ass** [comment]
Well, I think I nailed it. 🎉 
Most parts, such as `activateCharging()` already existed and just needed to be pieced together.

#### Initial Test Results:

- `go to` button __ON__ → vacuum going to location ✅
- vacuum driving to location → `go to` button stays __ON__ ✅ 
- vacuum is at location → `go to` button stays __ON__ ✅ 
- `go to` button __OFF__ while still moving → movement canceled, return to dock ✅ 
- `go to` button __OFF__ while at location → return to dock ✅ 
- `go to` button __OFF__ by automation (for example after 3 minutes) → return to dock ✅ 

@maisun is this the behaviour you expected?

**Comment by maisun** [comment]
Hi @luc-ass , thank you for looking into it. Yeah that sounds perfect!

**Comment by luc-ass** [comment]
this has been resolved by #544

**Comment by afharo** [comment]
Thank you @luc-ass and @maisun for working this out! You rock!!!

I'll go ahead and close this issue then. Feel free to reopen if anything else is missing.
