### ISSUE TITLE
Room and/or Zone switches

### ISSUE THREAD

**Issue by Christian-CFP** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#546]
Hey, room and zone switches do not reset (shut off) after ending cleaning. They stay switched on.

**Comment by afharo** [comment]
That is true! After the _recent_ improvements that would allow us to select multiple rooms, it keeps them on for the next cleaning to clean those again.

Thank you reporting it!

**Comment by Christian-CFP** [comment]
So it is a bug right? Because why should they stay on after the cleaning is done.

**Comment by afharo** [comment]
I agree. They should be reset after the cleaning ends.

**Comment by luc-ass** [comment]
Wouldn't this be a typical application for HomeKit scenes?
Like:
```
Automation:
  When: Every Day at 10 a.m.
  Scene:
    - Living Room Vacuum: on
    - Hallway Vacuum: on
    - Vacuum Fan Speed: 100 %
  Disable: after 2 h
```
That would turn off all the previously enabled switches? From my point of view the permanently enabled switches could be useful if you wanted to clean the same rooms every das - though that could be solved with the above solution as well, now I think about it.

**Comment by nicolasbigot** [comment]
Same issue here. They used to reset automatically after cleaning. I also find that dock sensor does not report correct charging state for very long period of time.

**Comment by nicolasbigot** [comment]
> That is true! After the _recent_ improvements that would allow us to select multiple rooms, it keeps them on for the next cleaning to clean those again.
> 
> Thank you reporting it!

Is that a new behavior or a bug? Because that makes day to day cleaning harder that is used to be. Can you please make this optional or configurable?
Many thanks!

**Comment by afharo** [comment]
I would consider it a bug.

I'm away from my keyboard for a couple of days, so I can't fix it. I'll try to get it fixed when I get back at it.

Thank you for raising the awareness of this bugs and for your patience.

**Comment by afharo** [comment]
Can you confirm [v0.27.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.27.0) fixed these issues, please?

**Comment by Christian-CFP** [comment]
In the first try, yes!

Will test further. Thx.

**Comment by nicolasbigot** [comment]
Same here, seems to be fixed! Many thanks @afharo
