### ISSUE TITLE
Installed latest Update (v0.26.4 -> v0.26.5)/ No plugin was found for the accessory

### ISSUE THREAD

**Issue by DanielRechberg** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#547]
After installing v0.26.5 today and restarting the home bridge service, I get the following error now:

[9/10/2022, 3:02:55 PM] No plugin was found for the accessory "XiaomiRoborockVacuum" in your config.json. Please make sure the corresponding plugin is installed correctly.

Nothing else was changed and it worked for years now. Rolling back to prev version, doesn't resolve the issue.

BR Daniel

**Comment by DanielRechberg** [comment]
sorry I saw that the plugin could not get loaded because of some problems with "hap-nodes".... no clue why this happened because I didn't even do a home bridge upgrade. Anyway, manually installing/reinstalling with sudo npm install -g --unsafe-perm hap-nodejs@latest helped.

working again!

**Comment by sorriso93** [comment]
Lucky you, I tried the same with no success
