### ISSUE TITLE
[HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

### ISSUE THREAD

**Issue by mpuff** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#551]
when I activate this plugin in the latest version, I get an error [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null and the container is restarting all the time.

**Comment by afharo** [comment]
would you mind providing more logs, please?

Can you try if applying the same fix as in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/547 fixes your issue?

**Comment by mpuff** [comment]
I found this in the logs:

[9/13/2022, 9:07:55 AM] [Mi Robot Vacuum] Initializing XiaomiRoborockVacuum accessory...
[9/13/2022, 9:07:55 AM] [Mi Robot Vacuum] [Model=unknown] DEB getDevice | Discovering vacuum cleaner
[9/13/2022, 9:07:55 AM] [Mi Robot Vacuum] [Model=unknown] getRoomMap | No vacuum cleaner is discovered yet.
[9/13/2022, 9:07:55 AM] [Mi Robot Vacuum] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[9/13/2022, 9:07:55 AM] [Mi Robot Vacuum] [Model=unknown] DEB getServices

**Comment by afharo** [comment]
AFAIK, HB shouldn't crash from the errors in that log. But I'll take a look. Thanks for raising the issue.

**Comment by xkyle22x** [comment]
I also have the same issue. 
Here is my logs ![image](https://user-images.githubusercontent.com/66627364/190261853-1e1fab44-7ec5-4bf7-8380-39966c2366ab.png)

**Comment by afharo** [comment]
@xkyle22x does the server crash for you as well?

**Comment by xkyle22x** [comment]
No it just keeps trying every 2 mins to find connection

**Comment by mpuff** [comment]
The docker container is in a bootloop

**Comment by xkyle22x** [comment]
> @xkyle22x does the server crash for you as well?

**Comment by xkyle22x** [comment]
![image](https://user-images.githubusercontent.com/66627364/190322386-7aa10dad-ebbb-46fa-87fd-310be7d642ba.png)

**Comment by xkyle22x** [comment]
![image](https://user-images.githubusercontent.com/66627364/190322440-1dcb70a3-b46a-4f4c-9370-bce6738571d0.png)![image](https://user-images.githubusercontent.com/66627364/190322469-8588335a-95c6-4a5c-91eb-6c284c0e75b2.png)![image](https://user-images.githubusercontent.com/66627364/190322512-f8d9f3d5-d0b2-479d-b213-9b6703285345.png)

**Comment by afharo** [comment]
I see... FWIW, the errors shown in the logs are expected: the plugin didn't manage to connect, and homebridge is requesting values from the accessories, which cannot be fetched because it's not connected.

@xkyle22x from the logs, I don't think HB is crashing in your case... so, IMO, it's a different issue to @mpuff's 

-----

Now... to fix the _Could not connect to device_ issue, I'd like to validate that the IP and tokens are correct, would you both mind running the command below?

```sh
miio-vacuum inspect ip-address --token tokenAsHex
```

Replacing the `ip-address` and the `tokenAsHex` with the values you placed in your config.

What does the response show?

**Comment by xkyle22x** [comment]
I know that the ip is correct 100% because I can see it in my router and it has a static ip. 

Also I don't know if the token can change or not but this has worked perfectly for 2 years now with that token. 

Is it possible for the token to change?

**Comment by mpuff** [comment]
All the other items are unavailable when I have activated this plugin, even I deactivate it, all others are online

**Comment by xkyle22x** [comment]
> I see... FWIW, the errors shown in the logs are expected: the plugin didn't manage to connect, and homebridge is requesting values from the accessories, which cannot be fetched because it's not connected.
> 
> 
> 
> @xkyle22x from the logs, I don't think HB is crashing in your case... so, IMO, it's a different issue to @mpuff's 
> 
> 
> 
> -----
> 
> 
> 
> Now... to fix the _Could not connect to device_ issue, I'd like to validate that the IP and tokens are correct, would you both mind running the command below?
> 
> 
> 
> ```sh
> 
> miio-vacuum inspect ip-address --token tokenAsHex
> 
> ```
> 
> 
> 
> Replacing the `ip-address` and the `tokenAsHex` with the values you placed in your config.
> 
> 
> 
> What does the response show?

Any ideas?

**Comment by mpuff** [comment]
i have the vacuum cleaner also in openhab, and I can control it with the ip and token I use also in this plugin

**Comment by afharo** [comment]
> Is it possible for the token to change?

@xkyle22x it could change for a few reasons. One of them is reconfiguring it in the Xiaomi App, the wifi, or opening it in the Roborock app. There could be other reasons, but those are well known ones. I would suggest you double check extracting the token again. I found this option to be the easiest one: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

**Comment by afharo** [comment]
> All the other items are unavailable when I have activated this plugin, when I deactivate it, all others are online

That makes sense if HB is restarting, as it will stop all other plugins as well.

> i have the vacuum cleaner also in openhab, and I can control it with the ip and token I use also in this plugin

I'm not aware of how openhab works. How did you retrieve the token? 

@mpuff,would you mind validating that it matches the output of the token you get with this method: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor?

**Comment by mpuff** [comment]
Openhab is extracting the token from the cloud, I think it's similar to your link how this is working

**Comment by mpuff** [comment]
I checked with your scribt, its the same token

**Comment by yangirov** [comment]
Unfortunately, I have same situation. I did exactly the same actions.

I am sure of the correctness of the token, I received it using [xiaomi-cloud-tokens-extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) and Mi Home backup. 

I have already written about it [#444](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/444#issuecomment-1287765242).

**Comment by afharo** [comment]
I think this was fixed in the last release. The process should not crash anymore. I'll go ahead and close this issue. Feel free to reopen if I missed anything.

**Comment by yangirov** [comment]
@afharo I just checked it right now via 0.28.1, but it doesn't work :-(

Maybe you need other data, logs? How can I help you?

P.S. But when I used [python-miio](https://github.com/rytilahti/python-miio) everything is OK.
![image](https://user-images.githubusercontent.com/32175431/215774125-cfa4e0f6-fe25-4bf9-b8d7-7fdc6591a5de.png)

**Comment by afharo** [comment]
@yangirov, I can see your model is part of the Dreame series, unfortunately that's not supported yet.

You can subscribe to the issue https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/434 to receive any updates when I make progress with that model.
