### ISSUE TITLE
IOS 16 Error

### ISSUE THREAD

**Issue by HuettmannH** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#556]
after installing the update to IOS 16 on my phone and update all my HomePods, I can no longer control the Roborock S7 Max via the app Eve. The room names are no longer displayed. However, they are displayed in Homebridge. Does anyone else have this problem? Has anyone already solved the problem?

**Comment by latrine666** [comment]
I have the same problem. Also the same with Xiamo fans. I think it’s a conversion thing to the new home app from Apple.

**Comment by afharo** [comment]
It's a bug on iOS16 and it affects most homebridge plugins.

For more references, look at this other issue: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552

I'll go ahead and close this issue since there's nothing we can do from the plugin end.
