### ISSUE TITLE
Vacuum's HomeKit service doesn't go off when vacuum finishes work. 

### ISSUE THREAD

**Issue by WojtekWro** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#559]
After finish work my vacuum returns to the dock, but plugging shows it still working.
Model=viomi.vacuum.v7 

extract from log. 

[9/24/2022, 8:07:54 AM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: Call to device timed out. See https://homebridge.io/w/JtMGR for more info.

**Comment by arek190491** [comment]
I have the same problem. After finish my rooms the buttons are always on.

**Comment by afharo** [comment]
Can you confirm [v0.27.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.27.0) fixed these issues, please?

**Comment by WojtekWro** [comment]
@afharo thank you for your help, however I have still the same issue.

**Comment by WojtekWro** [comment]
What is important, I have two vacuums. Only viomi.v7 faces this issue.

**Comment by afharo** [comment]
@WojtekWro Thanks for confirming... `viomi` models have a very limited support at the moment.

I'll try to prioritize improving compatibility for the next versions.

**Comment by WojtekWro** [comment]
@afharo after a second try I am glad to tell you that it works fine :) 
Now status changes to off after vacuum finishes job and announces command “going back to the dock”. I am not sure, but in the past the status went off when vacuum riches the dock. For me it is fine. 
the most important, that I know when it finished job :) 

thank you again.

**Comment by WojtekWro** [comment]
@afharo I ma sorry, but after a couple of tries it seems that the issue still occurs.

**Comment by afharo** [comment]
OK! Thanks for confirming @WojtekWro! Ditto to the above: I'll try to prioritize improving `viomi` support in future releases :)
