### ISSUE TITLE
Room names are all the same 

### ISSUE THREAD

**Issue by Reddyzinho** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#563]
I have been using this plugin , but now after some updates from HomeKit / Homebridge, all the room names are ….equal. 

My vacuum cleaner calls “ASPIRADOR” (Portuguese), and all the six accessories (room names), have the same name as well. When I change this name in the HomeKit, it goes ok, but when restarting the Homebridge, bye bye names ;) 
Anyhting I’m doing wrong? It’s a bug? 

HEre is my CONFIG

"name": "Aspirador",
            "ip": "————————-",
            "token": "—————————-",
            "serviceType": "fan",
            "waterBox": true,
            "dustBin": false,
            "dustCollection": false,
            "disableCareServices": false,
            "silent": false,
            "pause": false,
            "pauseWord": "Parár aspirador",
            "findMe": true,
            "findMeWord": "Aonde está o aspirador",
            "goTo": false,
            "goToWord": "go to coordinates",
            "goToX": 25500,
            "goToY": 25500,
            "dock": false,
            "cleanword": "Aspirar",
            "roomTimeout": 1,
            "autoroom": false,
            "rooms": [
                {
                    "name": "Quarto",
                    "id": 16
                },
                {
                    "name": "Cozinha",
                    "id": 17
                },
                {
                    "name": "Entrada",
                    "id": 18
                },
                {
                    "name": "Casa de Banho",
                    "id": 19
                },
                {
                    "name": "Sala de Estar",
                    "id": 21
                },
                {
                    "name": "Tapete",
                    "id": 22
                }
            ],
            "accessory": "XiaomiRoborockVacuum"

**Comment by afharo** [comment]
Unfortunately, the issues with showing wrong names in iOS16 is a bug on iOS16 itself. A related issue in this repo is https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552. It has a link to another issue in `homebridge` where folks are complaining about the same issue in other plugins.

The workaround is to manually rename them. Follow the links for more details.

I'll go ahead and close this issue for now. Feel free to reopen it if you think I missed any detail specific about this issue.
