### ISSUE TITLE
"Hey Siri, clean room x" not working on Homepod but working from my Iphone

### ISSUE THREAD

**Issue by Guitou031** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#567]
Hello

I have a regression form since last update of the plugin : I have set-up the plugin in Hombridge everything is fine. I have the rooms set-up and it works with the swithces buttons from Homekit on my Iphone and Ipad.
When I say "hey Siri clean Room A" : the switch "Clean Room A" is turned on and it works fine.

I was able to do that also from my Homepod also with the same voice command, but recently it no longer works : "Sorry I did not find this in your house" (I am french so I translate...).

Hope I am did not duplicate this issue with something already existing, I have looked for something before to write to you.

Thank you for your help !

Regards,

**Comment by Guitou031** [comment]
I add that My model is Roborock S7. Not new modeil

**Comment by phi-lip** [comment]
I have the same problem with my Roborock S6.

**Comment by diwiesign** [comment]
I have the same problem with the Roborock S6 too.

**Comment by afharo** [comment]
We don't treat iPhone and HomePod requests differently. I'd say this is a bug on iOS16... They already introduced a regression themselves when they named all accessories the same. Refer to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552 for more context.

**Comment by afharo** [comment]
Closing this issue as it's confirmed to be a a bug from iOS16. Refer to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552 for more context and potential workarounds.
