### ISSUE TITLE
Slows down homebridge 

### ISSUE THREAD

**Issue by BenjiBizz** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#577]
Pls fix this 

thanks 

![7FE0B528-8262-4AB3-AAE5-1E52F714AD47](https://user-images.githubusercontent.com/115275941/194599657-6955a476-e90c-43d2-abeb-3ac263f55957.jpeg)

**Comment by afharo** [comment]
Hi! I just tested this with my robot, and I couldn't see this line at all.

Looking where the warning is generated, it seems that it's triggered when the plugin takes longer than 30s to respond: https://github.com/homebridge/HAP-NodeJS/blob/f6629643e481032f2b166ca797315eacbea232ec/src/lib/Service.ts#L594-L613

The plugin triggers the Serial Number request as soon as it's requested. Typically, in a local network, it shouldn't take more than a couple of seconds to respond.

According to the rest of the logs you see, is your robot correctly connected and working, or is it still trying to establish connection when these warnings are printed?

**Comment by BenjiBizz** [comment]
Everything is fine. Robot works. 

Get this warning from Time to Time. Last des days- nothing warning. Dont know whats going on.

**Comment by afharo** [comment]
I'll close this issue. I think the latest version improved this a bit, and the warnings should not be shown... Feel free to reopen if that's not the case.
