### ISSUE TITLE
Homebridge service while when plugin activated

### ISSUE THREAD

**Issue by GaryEl** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#609]
Hi my homebridge not work whenthe plugin is activated :

27/11/2022, 08:56:21] [Roborock Q7] [Model=unknown] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[27/11/2022, 08:56:21] Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:218:21)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[27/11/2022, 08:56:21] Got SIGTERM, shutting down Homebridge...

**Comment by ablyes** [comment]
I'm facing the same problem 

{code}
[28/11/2022 18:25:17] [Alfred] [Model=unknown] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[28/11/2022 18:25:17] Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:218:21)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7){code}

**Comment by afharo** [comment]
Hi! Thanks for reporting. Is it crashing homebridge or breaking other plugins' functionality? This plugin should automatically retry the connection every 2 minutes.

Also, have you validated the token and IP are correct? Please, follow the last section of the README (https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#is-my-model-supported) to validate those are correct.

**Comment by ablyes** [comment]
It's crashing homebridge. From my side, i have integrated in jeedom as a plugin. 
Jeedom is warning me that the plugin is broken. 
It's not braking others plugins. 
The IP is correct, the token i don't know if Xiaomi is changing that sometimes. But anyway, we should not have a crash, just a warning that something is wrong, ip or token, or whatever.

**Comment by afharo** [comment]
I agree that it should not crash! I'll take a look to figure out where is that crash coming from.

**Comment by GaryEl** [comment]
Hi this is crash of homebridge, and yes token and IP are good, the plugin was working very well last week and there was this bug and since then I can't activate it because it makes homebridge crack

![4AD579BB-E4FA-47FD-BED4-0DE0285D68B1](https://user-images.githubusercontent.com/70843832/204688831-edc4636c-ec25-460c-843e-973c82e05d31.png)

![6E0F652A-55F5-42B6-98A3-B6BD16D14DD2](https://user-images.githubusercontent.com/70843832/204688870-2729bbab-3989-4d5f-87d1-5d75bc427c8d.png)

**Comment by afharo** [comment]
Understood! I'll try to catch the part where we throw the error that crashes the whole thing

**Comment by sanychonline** [comment]
This bug occurs when device is out of wifi connection while this plugin is trying to discover device. In my case I decide to revert back to v0.23.0
It is a most stable version as for me…

**Comment by afharo** [comment]
Apologies... I didn't have much time to look at this... Life's getting in the way lately... I'll see if I can spend some time on this tonight.

**Comment by afharo** [comment]
Hey! It took me a while to replicate the crash on my side...

Q: How does your configuration look like? I noticed that enabling the Room Service crashed when failing to connect (and I wonder if there may be other optional services that make it crash as well).

**Comment by afharo** [comment]
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.28.1 should have fixed the issue
