### ISSUE TITLE
Room cleaning / Where is no longer accessible in new Home app

### ISSUE THREAD

**Issue by rachedamer** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#610]
With the update in the Apple Home app in Ventura and iOS 16 as well as with the last Homepod Mini update I can no longer access the room cleaning / "where is" / other additional functions via voice. In the Home app, I see a "Locky" (my vacuum cleaner's name) entry with nine sub-entries that are all called "Locky". On my iPad where there is still iOS 15, these entries have useful names such as "Locky Where are you", "Start cleaning Kitchen", "Start cleaning Living room". When I use voice control on the iPad, everything works as expected. But on the Homepod, iPhone or Macbook, I can only start (and sometimes, not always) stop Locky, not make use of any of the additional features.

**Comment by afharo** [comment]
It's a bug on iOS16 that affects many `homebridge` plugins. Please refer to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552 where there's a link to the original `homebridge` issue. There's a workaround to fix that.

I'll go ahead and close this issue as there's nothing we can do in this plugin to fix it (we register the accessories with the right names).
