### ISSUE TITLE
iOS 16: can group accessories but can't ungroup them

### ISSUE THREAD

**Issue by ylexus** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#631]
I have multiple accessories exposed for my Roborock: main vacuum as the fan and switches for rooms and pausing. They are all shown as single tiles in the iOS Home app. If I go to any accessory's settings in that app I can tap on "Group With Other Accessories..." 

![image](https://user-images.githubusercontent.com/6009806/210139626-9b39d15b-29fc-40ea-912f-f35a6e674c23.png)

and group some of these together. However, it's then impossible to fully ungroup them. A minimum of two accessories will always remain. Inside the group, each accessory's settings is supposed to have an option to be removed from the group, but the roborock accessories don't have that option. 

![image](https://user-images.githubusercontent.com/6009806/210139639-dfd985d7-049d-4990-90f5-b3969838e87e.png)

You can still untick them in the group settings and this remove, but as I said at least two must always remain. 

 
Spent a lot of time with a senior Apple support advisor, but they could not solve it and expressed the opinion that even if I raise this with Apple engineering they are likely to reject the issue as it's a non-certified accessory. The advisor confirmed that the option to remove from the group does exist on compatible certified switches that he tried. 

The workaround here is leave in the group only two accessories that you can disable in the homebridge roborock plugin settings, then disable them, then the group disappears, then re-enable the accessories. 

# Versions
iOS 16.2

homebridge-config-ui-x v4.50.2

Node.js Version	v16.18.1

homebridge-xiaomi-roborock-vacuum v0.28.1

Vacuum Model : roborock.vacuum.s5e, Firmware Version : 4.1.2_1662, Plug-In Version : MI_MDX_2774

**Comment by afharo** [comment]
That's an interesting behaviour. IMO, this weird behaviour should be looked at by the `homebridge` folks because this plugin doesn't do anything special when registering the services.

Would you mind opening the issue in https://github.com/homebridge/homebridge?

Feel free to ping me there so I can also follow up :)

**Comment by nttu8192** [comment]
I got the same issue, what I've done is that go the the edit accessories in the group and choose the devices that is Homekit supported natively (ie. those devices that was not added to homekit via homebridge), then you will see the option to ungroup in setting

**Comment by afharo** [comment]
Thanks for the pointers @nttu8192! 🧡 

As this is something that cannot be fixed at the plugin level. I'll go ahead and close the issue. Feel free to reopen if you think there's anything we can do on the plugin side.
