### ISSUE TITLE
S6 Zone cleaning

### ISSUE THREAD

**Issue by marithpl** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#76]
Hey,

I would like to ask if there is a zone cleaning support for new S6 roborock?

I'm wondering to buy Roborock S5/S6 with working zone cleaning via HomeKit.

**Comment by suxus-zz** [comment]
Hello, i had an S5 so far and have used the Homebridge Xiaomi Roborock Vacuum Zones Plugin for zone cleaning. Now we have bought the S6 and the Homebridge Xiaomi Roborock Vacuum Zones does not support the S6 and as it looks the plugin is no longer being developed. Can you maybe implement zone cleaning with your plugin?

Thank you very much

**Comment by afharo** [comment]
Hi @suxus-zz, thank you for your feedback.

Are you talking about [this plugin](https://github.com/Smileydude/homebridge-xiaomi-roborock-vacuum)?

I can give it a look and check how possible it is to migrate its logic to this plugin.

**Comment by suxus-zz** [comment]
Yes i'm talking from this plugin and at the moment it will not works with the S6.

**Comment by afharo** [comment]
OK, thanks! I'll have a look at it tomorrow evening if that's ok :)

**Comment by suxus-zz** [comment]
Yes that's great, thank you very much

**Comment by suxus-zz** [comment]
Hello is the implementation from the zone cleaning with the S6, from the code not possible or is this not in the planing from the developer?

**Comment by afharo** [comment]
I think it is possible and I’m planning to get to it at some point. But I can only do this in my spare time and lately it’s not much. Sorry.
I’ve been prioritising fixing bugs over new features.
However, rest assured I won’t forget about this.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
You can take look at this https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum

Its possible to clean rooms without coordinates, just with the index

**Comment by Kienz** [comment]
For Xiaomi Robot Vacuum 1st gen rooms are not available in the app. Ist it possible to use "app_zoned_clean" as an alternative for older models?
https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/zoned_clean.md

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i will take a look for switch between the models and then use right function.
will expand the config for that. please stay tuned

**Comment by afharo** [comment]
Thank you @c-o-m-m-a-n-d-e-r 

I think it's not a matter of one or the other. It should be just another feature where we can define zones. 

This plugin has an implementation about zones:
https://github.com/Smileydude/homebridge-xiaomi-roborock-vacuum

Maybe we can get it migrated to this one. Although it will be hard to retrieve the right coordinates to "paint" the map in the config... We can start by doing this as a manual update (like that plugin did) and in the future maybe come up with an actual UI to draw the zones on top of the map.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Would you please test this commit:

`npm install --save c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum#c6def417002d92f96d5003c718c9cf535fdbd3e0`

i started implementing Zone cleaning in there.
You can configure via config ui or direct into config.

Parameter "zones" : [{"name": "Zone Name", "zone" : "x1, y1, x2, y2, repeat"}]

Please report back

**Comment by c-o-m-m-a-n-d-e-r** [comment]
In addition this can work for Gen 1 Devices i think.

**Comment by Kienz** [comment]
I will test it. One thing: "zone" should be an array of zones to define muliple zones for eg. one room. Because it's not allways possile to define a room by one zone.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Could you give me an example please :-)

**Comment by Kienz** [comment]
It starts the zone cleaning - but only for a fews seconds. Then it goes back to dock.
```
[2/28/2020, 4:41:14 PM] [Saugroboter] ACT setCleaning | rockrobo.vacuum.v1 | Start cleaning Zone [25810,16300,29810,20100,1],[28800,19900,30400,23500,1], not charging.
[2/28/2020, 4:41:14 PM] [Saugroboter] INF changedPause | rockrobo.vacuum.v1 | Paused not possible, no cleaning
[2/28/2020, 4:41:39 PM] [Saugroboter] MON changedCharging | rockrobo.vacuum.v1 | ChargingState is now false
[2/28/2020, 4:41:39 PM] [Saugroboter] INF changedCharging | rockrobo.vacuum.v1 | Charging is cancelled
[2/28/2020, 4:41:39 PM] [Saugroboter] INF changedCharging | rockrobo.vacuum.v1 | Robot not anymore in dock.
[2/28/2020, 4:41:39 PM] [Saugroboter] INF changedPause | rockrobo.vacuum.v1 | Paused not possible, no cleaning
[2/28/2020, 4:42:09 PM] [Saugroboter] MON changedCharging | rockrobo.vacuum.v1 | ChargingState is now true
[2/28/2020, 4:42:09 PM] [Saugroboter] INF changedCharging | rockrobo.vacuum.v1 | Charging is active
[2/28/2020, 4:42:09 PM] [Saugroboter] INF changedCharging | rockrobo.vacuum.v1 | Robot was docked.
```

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Mhhh good question, can you try with a really simpel zone for the beginning?

btw thanks for testing!

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i think i found something ... let me create an commit...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Please test with this Version again

`npm install --save c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum#104a5b0cf56d1b3d4cfeb8ae51724a2458847b71`

**Comment by Kienz** [comment]
Still testing. Tested some simple zones but it starts and stops after 2s and is going back to dock. If I start zoned cleanup from Mi App all zone switches toggle on. Is it possible to get zone coordinates from Mi App?
![6285133E-F840-40DA-850D-73AEEB6ED197](https://user-images.githubusercontent.com/954545/75610939-13ee1680-5b16-11ea-9057-0a2cc97caef9.png)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Yes i think i found a bug ... PR is created in miio class.
don't know how to get coordinates from mi app ...

I think there is a lot to do for correct button handling etc. when controlling from outside.

**Comment by C3dr11c** [comment]
I have the same effect. When I use the AutoRoom function (rooms are named in the MiHome app) and start cleaning a room, the roborock returns to the dock after a few seconds

**Comment by afharo** [comment]
I think this issue can be closed. If anyone thinks it's not solved yet, please feel free to reopen it and provide your reasons.

Thank you all!
