### ISSUE TITLE
Can’t disable mopping

### ISSUE THREAD

**Issue by czerepsky** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#764]
I have enabled mopping but I can’t disable it when I only want to vacuum. When I first disable mopping and start vacuum after few sec mopping is emending automatically. When I tried to disable mopping during vacuum, roborock is stoping whole cleaning and go back to docking station. My model is S7.

**Comment by pelletip** [comment]
I have the Q Revo and would also love to be able to have the ability to select mopping and vaccuming separately or have them both.

**Comment by afharo** [comment]
I think I found the bug. I'll work on it straight away

**Comment by afharo** [comment]
It should be fixed in [v0.29.1](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.29.1). Please, let me know if it isn't.
