### ISSUE TITLE
URL List to not break the connection?

### ISSUE THREAD

**Issue by pottersfield** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#766]
Hi,

I am facing an issue where, if I enable a specific blocklist for xiaomi related devices on my DNS I no longer get a connection to my Roborock. If I disable that list, it immediately works. 

My blocklist contains these links:

https://raw.githubusercontent.com/pottersfield/adguard/main/xiaomi_blocklist.txt

And my allowlist contains these links:

https://raw.githubusercontent.com/pottersfield/adguard/main/xiaomi_allowlist.txt

If you could tell me which links I would need to move from block to allow I would be much appreciated. 

PS: I am only facing this issue with this xiaomi plugin. For my other xiaomi devices I am using another one which works just fine, so it seems your plugin relies on specific URL's for a proper connection. 

Thx in advance!

**Comment by afharo** [comment]
Hey @pottersfield!

AFAIK, this plugin doesn't rely on any public URL. However, it uses UDP to communicate with the device. Could that be the cause of the connection being blocked?

Can you point me at any of the other plugins that work for you? I'd like to check if they managed to communicate over TCP. If I can copy that from them, I'll also solve some other issues from other users :)

**Comment by pottersfield** [comment]
Hi @afharo 
Thx for your answer.

I am mainly using [homebridge-miot](https://github.com/merdok/homebridge-miot) 

Hmmm if there is not really a connection to a URL it's strange that it cannot even connect to the device internally. As soon as I disable the blocklist and restart the plugin it establishes the connection, weird...

thanks for looking into this!

**Comment by pottersfield** [comment]
@afharo 
Any update on this? 👀

**Comment by afharo** [comment]
@pottersfield, I just checked the repo you linked and the main difference is that mine sends the UDP packets in broadcast mode, while the other repo doesn't.

Can you try commenting https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/757cef36262199676834126ccf29a4e9cb81bdab/src/miio/lib/network.js#L133 and https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/757cef36262199676834126ccf29a4e9cb81bdab/src/miio/lib/network.js#L131 in your installation to see if it improves things on your end?

**Comment by pottersfield** [comment]
![image](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/assets/22965340/d2ed009e-9134-44d9-98b4-316595ecc8eb)


Like this?

**Comment by afharo** [comment]
That is correct! Yes! Let me know if that works for you. If it does, I'll make that change permanent :)

**Comment by pottersfield** [comment]
@afharo Okay, so for the first day, it still works, no dropped connection, the blocklist blocks constantly connections and everything seems fine. 

I will report back in a couple of days, because sometimes it took some time to kick in before the issue (re)appeared. 

If your plugin does not break something else with commenting these two lines you could update it permanently. But if only my specific environment needs this tweak, I could also adjust it if needed after each update, thats not a big deal for me! :) Thx in the meantime! 🫶

**Comment by afharo** [comment]
Thank you for the updates and the testing 🧡!

Please, keep me posted. 

If we make this change permanent, I'd try to include a config flag to revert it in case someone finds any connection issues.

**Comment by pottersfield** [comment]
@afharo so after 3 days of testing it is still stable, no drops no connection loss, automations are running properly etc. and it still blocks outgoing connections via dns filters. For the moment, I am 95% sure that commenting those two lines fixed my setup! 🎉

**Comment by pottersfield** [comment]
@afharo It is back to a very unstable system. I had to reset the settings, reconfigure my roborock, disable the blocklist and then step by step bringing it back. It even removed my rooms, so I had to configure them as well. Right now it was able to work with the uncommented network.js file and the blocklist re-enabled... So I really do not understand why it works for a certain time and then it crashes again... Is there anything else I could provide you with to see if something else is broken on my side? :(

**Comment by pottersfield** [comment]
OMG maybe I found another possible rootcause.
For whatever reason connected my Mac Studio to my Home Network via WiFi eventhough I am connected with Ethernet. Maybe that screws up some things. I disconnected the WiFi and will test further.

**Comment by afharo** [comment]
Hahaha! I can see you're having fun with multiple tests. Let me know if I can help in any way.

**Comment by pottersfield** [comment]
5days with no issues. I will close the issue for now as it seems we finally sorted out everything! 😍
