### ISSUE TITLE
Another connexion problem

### ISSUE THREAD

**Issue by Dikky1984** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#860]
Hi guys !

I just received a new Roborock Q5 Pro (Model : roborock.vacuum.a72) and wanted to get it on my Home app using HB, but I can't ...

I could retrieve the token using Xiaomi Home app with the Xiaomi cloud tokens extractor. Unfortunately, using the token and the IP address in the Config.json file doesn't work. I still get this error :

 **[12/28/2023, 1:13:38 AM] [Roborock] [Model=unknown] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout**

I switched on the Roborock app and came back on the Xiaomi Home app to change the token. But even with the new token I still get the same error in HB.

I use a TP Link Deco X60 wifi mesh. The Roborock is connected in 2.4 Ghz and my Mac mini (homebridge server) on the 5 Ghz. I forced the 2.4 Ghz on the Mac mini to be on the same channel as the Roborock, but it didn't help neither ...

I also tried the following command with the right IP address and token : miio-vacuum inspect id-or-address --token tokenAsHex but I always get the same message :

**Mac-mini:~ user$ miio-vacuum inspect 192.168.XX.XX --token XXXXXXXXXXXXXXXXXXXXXXXXXXXX
 INFO  Attempting to inspect 192.168.XX.XX
 WARNING  Could not find device**

Is the Q5 Pro not supported ?

If it is supported, what do I do wrong ? I searched and try during hours now, but can't find any hint of what goes wrong ...

Thanks for your help !

**Comment by Dikky1984** [comment]
OK, finally I could get it working with Wifi settings. My Mac mini (homebridge server) was not correctly configured on the Wifi mesh network and couldn't talk with the Roborock.

You did a great work with this plug-in ! Thank you so much !

**Comment by afharo** [comment]
@Dikky1984, I'm glad that you figured it out. Apologies for not responding earlier
