### ISSUE TITLE
add Roborock S7 Max Ultra water mode

### ISSUE THREAD

**Issue by gimprota76** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#868]
[Model=roborock.vacuum.a65] setWaterSpeed | Model does not support the water mode
Help me
Thank you

**Comment by gimprota76** [comment]
nothing new?

**Comment by netRunner0** [comment]
Please add

**Comment by jmago17** [comment]
Which model it is?

**Comment by netRunner0** [comment]
Roborock S7 MaxV Ultra

**Comment by afharo** [comment]
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.34.0 should fix it.
